/*
TenantsService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.1.2.5532
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TenantTeamUpdateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantTeamUpdateDto{}

// TenantTeamUpdateDto struct for TenantTeamUpdateDto
type TenantTeamUpdateDto struct {
	Name NullableString `json:"name,omitempty"`
	Description NullableString `json:"description,omitempty"`
	AvatarUrl NullableString `json:"avatarUrl,omitempty"`
	IsPublic *bool `json:"isPublic,omitempty"`
	BusinessUnitId NullableString `json:"businessUnitId,omitempty"`
	OrganizationProfileId NullableString `json:"organizationProfileId,omitempty"`
}

// NewTenantTeamUpdateDto instantiates a new TenantTeamUpdateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantTeamUpdateDto() *TenantTeamUpdateDto {
	this := TenantTeamUpdateDto{}
	return &this
}

// NewTenantTeamUpdateDtoWithDefaults instantiates a new TenantTeamUpdateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantTeamUpdateDtoWithDefaults() *TenantTeamUpdateDto {
	this := TenantTeamUpdateDto{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantTeamUpdateDto) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantTeamUpdateDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *TenantTeamUpdateDto) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *TenantTeamUpdateDto) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *TenantTeamUpdateDto) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *TenantTeamUpdateDto) UnsetName() {
	o.Name.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantTeamUpdateDto) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantTeamUpdateDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *TenantTeamUpdateDto) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *TenantTeamUpdateDto) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *TenantTeamUpdateDto) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *TenantTeamUpdateDto) UnsetDescription() {
	o.Description.Unset()
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantTeamUpdateDto) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl.Get()) {
		var ret string
		return ret
	}
	return *o.AvatarUrl.Get()
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantTeamUpdateDto) GetAvatarUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvatarUrl.Get(), o.AvatarUrl.IsSet()
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *TenantTeamUpdateDto) HasAvatarUrl() bool {
	if o != nil && o.AvatarUrl.IsSet() {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given NullableString and assigns it to the AvatarUrl field.
func (o *TenantTeamUpdateDto) SetAvatarUrl(v string) {
	o.AvatarUrl.Set(&v)
}
// SetAvatarUrlNil sets the value for AvatarUrl to be an explicit nil
func (o *TenantTeamUpdateDto) SetAvatarUrlNil() {
	o.AvatarUrl.Set(nil)
}

// UnsetAvatarUrl ensures that no value is present for AvatarUrl, not even an explicit nil
func (o *TenantTeamUpdateDto) UnsetAvatarUrl() {
	o.AvatarUrl.Unset()
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *TenantTeamUpdateDto) GetIsPublic() bool {
	if o == nil || IsNil(o.IsPublic) {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantTeamUpdateDto) GetIsPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublic) {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *TenantTeamUpdateDto) HasIsPublic() bool {
	if o != nil && !IsNil(o.IsPublic) {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *TenantTeamUpdateDto) SetIsPublic(v bool) {
	o.IsPublic = &v
}

// GetBusinessUnitId returns the BusinessUnitId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantTeamUpdateDto) GetBusinessUnitId() string {
	if o == nil || IsNil(o.BusinessUnitId.Get()) {
		var ret string
		return ret
	}
	return *o.BusinessUnitId.Get()
}

// GetBusinessUnitIdOk returns a tuple with the BusinessUnitId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantTeamUpdateDto) GetBusinessUnitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BusinessUnitId.Get(), o.BusinessUnitId.IsSet()
}

// HasBusinessUnitId returns a boolean if a field has been set.
func (o *TenantTeamUpdateDto) HasBusinessUnitId() bool {
	if o != nil && o.BusinessUnitId.IsSet() {
		return true
	}

	return false
}

// SetBusinessUnitId gets a reference to the given NullableString and assigns it to the BusinessUnitId field.
func (o *TenantTeamUpdateDto) SetBusinessUnitId(v string) {
	o.BusinessUnitId.Set(&v)
}
// SetBusinessUnitIdNil sets the value for BusinessUnitId to be an explicit nil
func (o *TenantTeamUpdateDto) SetBusinessUnitIdNil() {
	o.BusinessUnitId.Set(nil)
}

// UnsetBusinessUnitId ensures that no value is present for BusinessUnitId, not even an explicit nil
func (o *TenantTeamUpdateDto) UnsetBusinessUnitId() {
	o.BusinessUnitId.Unset()
}

// GetOrganizationProfileId returns the OrganizationProfileId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantTeamUpdateDto) GetOrganizationProfileId() string {
	if o == nil || IsNil(o.OrganizationProfileId.Get()) {
		var ret string
		return ret
	}
	return *o.OrganizationProfileId.Get()
}

// GetOrganizationProfileIdOk returns a tuple with the OrganizationProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantTeamUpdateDto) GetOrganizationProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrganizationProfileId.Get(), o.OrganizationProfileId.IsSet()
}

// HasOrganizationProfileId returns a boolean if a field has been set.
func (o *TenantTeamUpdateDto) HasOrganizationProfileId() bool {
	if o != nil && o.OrganizationProfileId.IsSet() {
		return true
	}

	return false
}

// SetOrganizationProfileId gets a reference to the given NullableString and assigns it to the OrganizationProfileId field.
func (o *TenantTeamUpdateDto) SetOrganizationProfileId(v string) {
	o.OrganizationProfileId.Set(&v)
}
// SetOrganizationProfileIdNil sets the value for OrganizationProfileId to be an explicit nil
func (o *TenantTeamUpdateDto) SetOrganizationProfileIdNil() {
	o.OrganizationProfileId.Set(nil)
}

// UnsetOrganizationProfileId ensures that no value is present for OrganizationProfileId, not even an explicit nil
func (o *TenantTeamUpdateDto) UnsetOrganizationProfileId() {
	o.OrganizationProfileId.Unset()
}

func (o TenantTeamUpdateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantTeamUpdateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.AvatarUrl.IsSet() {
		toSerialize["avatarUrl"] = o.AvatarUrl.Get()
	}
	if !IsNil(o.IsPublic) {
		toSerialize["isPublic"] = o.IsPublic
	}
	if o.BusinessUnitId.IsSet() {
		toSerialize["businessUnitId"] = o.BusinessUnitId.Get()
	}
	if o.OrganizationProfileId.IsSet() {
		toSerialize["organizationProfileId"] = o.OrganizationProfileId.Get()
	}
	return toSerialize, nil
}

type NullableTenantTeamUpdateDto struct {
	value *TenantTeamUpdateDto
	isSet bool
}

func (v NullableTenantTeamUpdateDto) Get() *TenantTeamUpdateDto {
	return v.value
}

func (v *NullableTenantTeamUpdateDto) Set(val *TenantTeamUpdateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantTeamUpdateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantTeamUpdateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantTeamUpdateDto(val *TenantTeamUpdateDto) *NullableTenantTeamUpdateDto {
	return &NullableTenantTeamUpdateDto{value: val, isSet: true}
}

func (v NullableTenantTeamUpdateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantTeamUpdateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


