/*
TenantsService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TenantTeamContactEnrollmentUpdateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantTeamContactEnrollmentUpdateDto{}

// TenantTeamContactEnrollmentUpdateDto struct for TenantTeamContactEnrollmentUpdateDto
type TenantTeamContactEnrollmentUpdateDto struct {
	BusinessTeamID NullableString `json:"businessTeamID,omitempty"`
	ContactID NullableString `json:"contactID,omitempty"`
}

// NewTenantTeamContactEnrollmentUpdateDto instantiates a new TenantTeamContactEnrollmentUpdateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantTeamContactEnrollmentUpdateDto() *TenantTeamContactEnrollmentUpdateDto {
	this := TenantTeamContactEnrollmentUpdateDto{}
	return &this
}

// NewTenantTeamContactEnrollmentUpdateDtoWithDefaults instantiates a new TenantTeamContactEnrollmentUpdateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantTeamContactEnrollmentUpdateDtoWithDefaults() *TenantTeamContactEnrollmentUpdateDto {
	this := TenantTeamContactEnrollmentUpdateDto{}
	return &this
}

// GetBusinessTeamID returns the BusinessTeamID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantTeamContactEnrollmentUpdateDto) GetBusinessTeamID() string {
	if o == nil || IsNil(o.BusinessTeamID.Get()) {
		var ret string
		return ret
	}
	return *o.BusinessTeamID.Get()
}

// GetBusinessTeamIDOk returns a tuple with the BusinessTeamID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantTeamContactEnrollmentUpdateDto) GetBusinessTeamIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BusinessTeamID.Get(), o.BusinessTeamID.IsSet()
}

// HasBusinessTeamID returns a boolean if a field has been set.
func (o *TenantTeamContactEnrollmentUpdateDto) HasBusinessTeamID() bool {
	if o != nil && o.BusinessTeamID.IsSet() {
		return true
	}

	return false
}

// SetBusinessTeamID gets a reference to the given NullableString and assigns it to the BusinessTeamID field.
func (o *TenantTeamContactEnrollmentUpdateDto) SetBusinessTeamID(v string) {
	o.BusinessTeamID.Set(&v)
}
// SetBusinessTeamIDNil sets the value for BusinessTeamID to be an explicit nil
func (o *TenantTeamContactEnrollmentUpdateDto) SetBusinessTeamIDNil() {
	o.BusinessTeamID.Set(nil)
}

// UnsetBusinessTeamID ensures that no value is present for BusinessTeamID, not even an explicit nil
func (o *TenantTeamContactEnrollmentUpdateDto) UnsetBusinessTeamID() {
	o.BusinessTeamID.Unset()
}

// GetContactID returns the ContactID field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TenantTeamContactEnrollmentUpdateDto) GetContactID() string {
	if o == nil || IsNil(o.ContactID.Get()) {
		var ret string
		return ret
	}
	return *o.ContactID.Get()
}

// GetContactIDOk returns a tuple with the ContactID field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TenantTeamContactEnrollmentUpdateDto) GetContactIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContactID.Get(), o.ContactID.IsSet()
}

// HasContactID returns a boolean if a field has been set.
func (o *TenantTeamContactEnrollmentUpdateDto) HasContactID() bool {
	if o != nil && o.ContactID.IsSet() {
		return true
	}

	return false
}

// SetContactID gets a reference to the given NullableString and assigns it to the ContactID field.
func (o *TenantTeamContactEnrollmentUpdateDto) SetContactID(v string) {
	o.ContactID.Set(&v)
}
// SetContactIDNil sets the value for ContactID to be an explicit nil
func (o *TenantTeamContactEnrollmentUpdateDto) SetContactIDNil() {
	o.ContactID.Set(nil)
}

// UnsetContactID ensures that no value is present for ContactID, not even an explicit nil
func (o *TenantTeamContactEnrollmentUpdateDto) UnsetContactID() {
	o.ContactID.Unset()
}

func (o TenantTeamContactEnrollmentUpdateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantTeamContactEnrollmentUpdateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BusinessTeamID.IsSet() {
		toSerialize["businessTeamID"] = o.BusinessTeamID.Get()
	}
	if o.ContactID.IsSet() {
		toSerialize["contactID"] = o.ContactID.Get()
	}
	return toSerialize, nil
}

type NullableTenantTeamContactEnrollmentUpdateDto struct {
	value *TenantTeamContactEnrollmentUpdateDto
	isSet bool
}

func (v NullableTenantTeamContactEnrollmentUpdateDto) Get() *TenantTeamContactEnrollmentUpdateDto {
	return v.value
}

func (v *NullableTenantTeamContactEnrollmentUpdateDto) Set(val *TenantTeamContactEnrollmentUpdateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantTeamContactEnrollmentUpdateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantTeamContactEnrollmentUpdateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantTeamContactEnrollmentUpdateDto(val *TenantTeamContactEnrollmentUpdateDto) *NullableTenantTeamContactEnrollmentUpdateDto {
	return &NullableTenantTeamContactEnrollmentUpdateDto{value: val, isSet: true}
}

func (v NullableTenantTeamContactEnrollmentUpdateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantTeamContactEnrollmentUpdateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


