/*
CatalogService

Testing ItemCategoriesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ItemCategoriesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ItemCategoriesAPIService CountItemCategoriesAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ItemCategoriesAPI.CountItemCategoriesAsync(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemCategoriesAPIService CreateItemCategoryAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ItemCategoriesAPI.CreateItemCategoryAsync(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemCategoriesAPIService DeleteItemCategoryAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var itemCategoryId string

		httpRes, err := apiClient.ItemCategoriesAPI.DeleteItemCategoryAsync(context.Background(), itemCategoryId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemCategoriesAPIService GetItemCategoriesAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ItemCategoriesAPI.GetItemCategoriesAsync(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemCategoriesAPIService GetItemCategoryByIdAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var itemCategoryId string

		resp, httpRes, err := apiClient.ItemCategoriesAPI.GetItemCategoryByIdAsync(context.Background(), itemCategoryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ItemCategoriesAPIService UpdateItemCategoryAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var itemCategoryId string

		httpRes, err := apiClient.ItemCategoriesAPI.UpdateItemCategoryAsync(context.Background(), itemCategoryId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
