/*
HrmsService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// JobOfferFieldsAPIService JobOfferFieldsAPI service
type JobOfferFieldsAPIService service

type ApiCreateJobOfferFieldAsyncRequest struct {
	ctx context.Context
	ApiService *JobOfferFieldsAPIService
	tenantId *string
	apiVersion *string
	xApiVersion *string
	jobOfferFieldRecordCreateDto *JobOfferFieldRecordCreateDto
}

func (r ApiCreateJobOfferFieldAsyncRequest) TenantId(tenantId string) ApiCreateJobOfferFieldAsyncRequest {
	r.tenantId = &tenantId
	return r
}

func (r ApiCreateJobOfferFieldAsyncRequest) ApiVersion(apiVersion string) ApiCreateJobOfferFieldAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiCreateJobOfferFieldAsyncRequest) XApiVersion(xApiVersion string) ApiCreateJobOfferFieldAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiCreateJobOfferFieldAsyncRequest) JobOfferFieldRecordCreateDto(jobOfferFieldRecordCreateDto JobOfferFieldRecordCreateDto) ApiCreateJobOfferFieldAsyncRequest {
	r.jobOfferFieldRecordCreateDto = &jobOfferFieldRecordCreateDto
	return r
}

func (r ApiCreateJobOfferFieldAsyncRequest) Execute() (*EmptyEnvelope, *http.Response, error) {
	return r.ApiService.CreateJobOfferFieldAsyncExecute(r)
}

/*
CreateJobOfferFieldAsync Create a job offer field

Links a job field to a job offer for the specified tenant.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateJobOfferFieldAsyncRequest
*/
func (a *JobOfferFieldsAPIService) CreateJobOfferFieldAsync(ctx context.Context) ApiCreateJobOfferFieldAsyncRequest {
	return ApiCreateJobOfferFieldAsyncRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return EmptyEnvelope
func (a *JobOfferFieldsAPIService) CreateJobOfferFieldAsyncExecute(r ApiCreateJobOfferFieldAsyncRequest) (*EmptyEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EmptyEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "JobOfferFieldsAPIService.CreateJobOfferFieldAsync")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/HrmsService/JobOfferFields"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.tenantId == nil {
		return localVarReturnValue, nil, reportError("tenantId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "tenantId", r.tenantId, "form", "")
	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/xml"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	// body params
	localVarPostBody = r.jobOfferFieldRecordCreateDto
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteJobOfferFieldAsyncRequest struct {
	ctx context.Context
	ApiService *JobOfferFieldsAPIService
	tenantId *string
	jobOfferFieldId string
	apiVersion *string
	xApiVersion *string
}

func (r ApiDeleteJobOfferFieldAsyncRequest) TenantId(tenantId string) ApiDeleteJobOfferFieldAsyncRequest {
	r.tenantId = &tenantId
	return r
}

func (r ApiDeleteJobOfferFieldAsyncRequest) ApiVersion(apiVersion string) ApiDeleteJobOfferFieldAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiDeleteJobOfferFieldAsyncRequest) XApiVersion(xApiVersion string) ApiDeleteJobOfferFieldAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiDeleteJobOfferFieldAsyncRequest) Execute() (*EmptyEnvelope, *http.Response, error) {
	return r.ApiService.DeleteJobOfferFieldAsyncExecute(r)
}

/*
DeleteJobOfferFieldAsync Delete a job offer field

Removes a job-offer field link record for the specified tenant.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param jobOfferFieldId
 @return ApiDeleteJobOfferFieldAsyncRequest
*/
func (a *JobOfferFieldsAPIService) DeleteJobOfferFieldAsync(ctx context.Context, jobOfferFieldId string) ApiDeleteJobOfferFieldAsyncRequest {
	return ApiDeleteJobOfferFieldAsyncRequest{
		ApiService: a,
		ctx: ctx,
		jobOfferFieldId: jobOfferFieldId,
	}
}

// Execute executes the request
//  @return EmptyEnvelope
func (a *JobOfferFieldsAPIService) DeleteJobOfferFieldAsyncExecute(r ApiDeleteJobOfferFieldAsyncRequest) (*EmptyEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EmptyEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "JobOfferFieldsAPIService.DeleteJobOfferFieldAsync")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/HrmsService/JobOfferFields/{jobOfferFieldId}"
	localVarPath = strings.Replace(localVarPath, "{"+"jobOfferFieldId"+"}", url.PathEscape(parameterValueToString(r.jobOfferFieldId, "jobOfferFieldId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.tenantId == nil {
		return localVarReturnValue, nil, reportError("tenantId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "tenantId", r.tenantId, "form", "")
	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetJobOfferFieldByIdAsyncRequest struct {
	ctx context.Context
	ApiService *JobOfferFieldsAPIService
	tenantId *string
	jobOfferFieldId string
	apiVersion *string
	xApiVersion *string
}

func (r ApiGetJobOfferFieldByIdAsyncRequest) TenantId(tenantId string) ApiGetJobOfferFieldByIdAsyncRequest {
	r.tenantId = &tenantId
	return r
}

func (r ApiGetJobOfferFieldByIdAsyncRequest) ApiVersion(apiVersion string) ApiGetJobOfferFieldByIdAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiGetJobOfferFieldByIdAsyncRequest) XApiVersion(xApiVersion string) ApiGetJobOfferFieldByIdAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiGetJobOfferFieldByIdAsyncRequest) Execute() (*JobOfferFieldRecordDtoEnvelope, *http.Response, error) {
	return r.ApiService.GetJobOfferFieldByIdAsyncExecute(r)
}

/*
GetJobOfferFieldByIdAsync Get job offer field by ID

Retrieves a specific job-offer field link record by its identifier.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param jobOfferFieldId
 @return ApiGetJobOfferFieldByIdAsyncRequest
*/
func (a *JobOfferFieldsAPIService) GetJobOfferFieldByIdAsync(ctx context.Context, jobOfferFieldId string) ApiGetJobOfferFieldByIdAsyncRequest {
	return ApiGetJobOfferFieldByIdAsyncRequest{
		ApiService: a,
		ctx: ctx,
		jobOfferFieldId: jobOfferFieldId,
	}
}

// Execute executes the request
//  @return JobOfferFieldRecordDtoEnvelope
func (a *JobOfferFieldsAPIService) GetJobOfferFieldByIdAsyncExecute(r ApiGetJobOfferFieldByIdAsyncRequest) (*JobOfferFieldRecordDtoEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *JobOfferFieldRecordDtoEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "JobOfferFieldsAPIService.GetJobOfferFieldByIdAsync")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/HrmsService/JobOfferFields/{jobOfferFieldId}"
	localVarPath = strings.Replace(localVarPath, "{"+"jobOfferFieldId"+"}", url.PathEscape(parameterValueToString(r.jobOfferFieldId, "jobOfferFieldId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.tenantId == nil {
		return localVarReturnValue, nil, reportError("tenantId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "tenantId", r.tenantId, "form", "")
	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetJobOfferFieldsAsyncRequest struct {
	ctx context.Context
	ApiService *JobOfferFieldsAPIService
	tenantId *string
	apiVersion *string
	xApiVersion *string
}

func (r ApiGetJobOfferFieldsAsyncRequest) TenantId(tenantId string) ApiGetJobOfferFieldsAsyncRequest {
	r.tenantId = &tenantId
	return r
}

func (r ApiGetJobOfferFieldsAsyncRequest) ApiVersion(apiVersion string) ApiGetJobOfferFieldsAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiGetJobOfferFieldsAsyncRequest) XApiVersion(xApiVersion string) ApiGetJobOfferFieldsAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiGetJobOfferFieldsAsyncRequest) Execute() (*JobOfferFieldRecordDtoListEnvelope, *http.Response, error) {
	return r.ApiService.GetJobOfferFieldsAsyncExecute(r)
}

/*
GetJobOfferFieldsAsync Get job offer fields

Retrieves job-offer field link records for the tenant. Filter with `$filter=JobOfferId eq '...'` or `JobFieldId eq '...'`.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetJobOfferFieldsAsyncRequest
*/
func (a *JobOfferFieldsAPIService) GetJobOfferFieldsAsync(ctx context.Context) ApiGetJobOfferFieldsAsyncRequest {
	return ApiGetJobOfferFieldsAsyncRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return JobOfferFieldRecordDtoListEnvelope
func (a *JobOfferFieldsAPIService) GetJobOfferFieldsAsyncExecute(r ApiGetJobOfferFieldsAsyncRequest) (*JobOfferFieldRecordDtoListEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *JobOfferFieldRecordDtoListEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "JobOfferFieldsAPIService.GetJobOfferFieldsAsync")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/HrmsService/JobOfferFields"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.tenantId == nil {
		return localVarReturnValue, nil, reportError("tenantId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "tenantId", r.tenantId, "form", "")
	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetJobOfferFieldsCountAsyncRequest struct {
	ctx context.Context
	ApiService *JobOfferFieldsAPIService
	tenantId *string
	apiVersion *string
	xApiVersion *string
}

func (r ApiGetJobOfferFieldsCountAsyncRequest) TenantId(tenantId string) ApiGetJobOfferFieldsCountAsyncRequest {
	r.tenantId = &tenantId
	return r
}

func (r ApiGetJobOfferFieldsCountAsyncRequest) ApiVersion(apiVersion string) ApiGetJobOfferFieldsCountAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiGetJobOfferFieldsCountAsyncRequest) XApiVersion(xApiVersion string) ApiGetJobOfferFieldsCountAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiGetJobOfferFieldsCountAsyncRequest) Execute() (*Int32Envelope, *http.Response, error) {
	return r.ApiService.GetJobOfferFieldsCountAsyncExecute(r)
}

/*
GetJobOfferFieldsCountAsync Count job offer fields

Counts job-offer field link records for the specified tenant.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetJobOfferFieldsCountAsyncRequest
*/
func (a *JobOfferFieldsAPIService) GetJobOfferFieldsCountAsync(ctx context.Context) ApiGetJobOfferFieldsCountAsyncRequest {
	return ApiGetJobOfferFieldsCountAsyncRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return Int32Envelope
func (a *JobOfferFieldsAPIService) GetJobOfferFieldsCountAsyncExecute(r ApiGetJobOfferFieldsCountAsyncRequest) (*Int32Envelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Int32Envelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "JobOfferFieldsAPIService.GetJobOfferFieldsCountAsync")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/HrmsService/JobOfferFields/Count"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.tenantId == nil {
		return localVarReturnValue, nil, reportError("tenantId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "tenantId", r.tenantId, "form", "")
	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPatchJobOfferFieldAsyncRequest struct {
	ctx context.Context
	ApiService *JobOfferFieldsAPIService
	tenantId *string
	jobOfferFieldId string
	apiVersion *string
	xApiVersion *string
	operation *[]Operation
}

func (r ApiPatchJobOfferFieldAsyncRequest) TenantId(tenantId string) ApiPatchJobOfferFieldAsyncRequest {
	r.tenantId = &tenantId
	return r
}

func (r ApiPatchJobOfferFieldAsyncRequest) ApiVersion(apiVersion string) ApiPatchJobOfferFieldAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiPatchJobOfferFieldAsyncRequest) XApiVersion(xApiVersion string) ApiPatchJobOfferFieldAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiPatchJobOfferFieldAsyncRequest) Operation(operation []Operation) ApiPatchJobOfferFieldAsyncRequest {
	r.operation = &operation
	return r
}

func (r ApiPatchJobOfferFieldAsyncRequest) Execute() (*EmptyEnvelope, *http.Response, error) {
	return r.ApiService.PatchJobOfferFieldAsyncExecute(r)
}

/*
PatchJobOfferFieldAsync Patch a job offer field

Partially updates an existing job-offer field link record for the specified tenant.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param jobOfferFieldId
 @return ApiPatchJobOfferFieldAsyncRequest
*/
func (a *JobOfferFieldsAPIService) PatchJobOfferFieldAsync(ctx context.Context, jobOfferFieldId string) ApiPatchJobOfferFieldAsyncRequest {
	return ApiPatchJobOfferFieldAsyncRequest{
		ApiService: a,
		ctx: ctx,
		jobOfferFieldId: jobOfferFieldId,
	}
}

// Execute executes the request
//  @return EmptyEnvelope
func (a *JobOfferFieldsAPIService) PatchJobOfferFieldAsyncExecute(r ApiPatchJobOfferFieldAsyncRequest) (*EmptyEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EmptyEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "JobOfferFieldsAPIService.PatchJobOfferFieldAsync")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/HrmsService/JobOfferFields/{jobOfferFieldId}"
	localVarPath = strings.Replace(localVarPath, "{"+"jobOfferFieldId"+"}", url.PathEscape(parameterValueToString(r.jobOfferFieldId, "jobOfferFieldId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.tenantId == nil {
		return localVarReturnValue, nil, reportError("tenantId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "tenantId", r.tenantId, "form", "")
	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/xml"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	// body params
	localVarPostBody = r.operation
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateJobOfferFieldAsyncRequest struct {
	ctx context.Context
	ApiService *JobOfferFieldsAPIService
	tenantId *string
	jobOfferFieldId string
	apiVersion *string
	xApiVersion *string
	jobOfferFieldRecordUpdateDto *JobOfferFieldRecordUpdateDto
}

func (r ApiUpdateJobOfferFieldAsyncRequest) TenantId(tenantId string) ApiUpdateJobOfferFieldAsyncRequest {
	r.tenantId = &tenantId
	return r
}

func (r ApiUpdateJobOfferFieldAsyncRequest) ApiVersion(apiVersion string) ApiUpdateJobOfferFieldAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiUpdateJobOfferFieldAsyncRequest) XApiVersion(xApiVersion string) ApiUpdateJobOfferFieldAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiUpdateJobOfferFieldAsyncRequest) JobOfferFieldRecordUpdateDto(jobOfferFieldRecordUpdateDto JobOfferFieldRecordUpdateDto) ApiUpdateJobOfferFieldAsyncRequest {
	r.jobOfferFieldRecordUpdateDto = &jobOfferFieldRecordUpdateDto
	return r
}

func (r ApiUpdateJobOfferFieldAsyncRequest) Execute() (*EmptyEnvelope, *http.Response, error) {
	return r.ApiService.UpdateJobOfferFieldAsyncExecute(r)
}

/*
UpdateJobOfferFieldAsync Update a job offer field

Updates an existing job-offer field link record for the specified tenant.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param jobOfferFieldId
 @return ApiUpdateJobOfferFieldAsyncRequest
*/
func (a *JobOfferFieldsAPIService) UpdateJobOfferFieldAsync(ctx context.Context, jobOfferFieldId string) ApiUpdateJobOfferFieldAsyncRequest {
	return ApiUpdateJobOfferFieldAsyncRequest{
		ApiService: a,
		ctx: ctx,
		jobOfferFieldId: jobOfferFieldId,
	}
}

// Execute executes the request
//  @return EmptyEnvelope
func (a *JobOfferFieldsAPIService) UpdateJobOfferFieldAsyncExecute(r ApiUpdateJobOfferFieldAsyncRequest) (*EmptyEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EmptyEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "JobOfferFieldsAPIService.UpdateJobOfferFieldAsync")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/HrmsService/JobOfferFields/{jobOfferFieldId}"
	localVarPath = strings.Replace(localVarPath, "{"+"jobOfferFieldId"+"}", url.PathEscape(parameterValueToString(r.jobOfferFieldId, "jobOfferFieldId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.tenantId == nil {
		return localVarReturnValue, nil, reportError("tenantId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "tenantId", r.tenantId, "form", "")
	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/xml"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	// body params
	localVarPostBody = r.jobOfferFieldRecordUpdateDto
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
