/*
AccountingService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the LoanApplicationCreateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoanApplicationCreateDto{}

// LoanApplicationCreateDto struct for LoanApplicationCreateDto
type LoanApplicationCreateDto struct {
	Id *string `json:"id,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// NewLoanApplicationCreateDto instantiates a new LoanApplicationCreateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoanApplicationCreateDto() *LoanApplicationCreateDto {
	this := LoanApplicationCreateDto{}
	return &this
}

// NewLoanApplicationCreateDtoWithDefaults instantiates a new LoanApplicationCreateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoanApplicationCreateDtoWithDefaults() *LoanApplicationCreateDto {
	this := LoanApplicationCreateDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LoanApplicationCreateDto) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoanApplicationCreateDto) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LoanApplicationCreateDto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LoanApplicationCreateDto) SetId(v string) {
	o.Id = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *LoanApplicationCreateDto) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoanApplicationCreateDto) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *LoanApplicationCreateDto) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *LoanApplicationCreateDto) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

func (o LoanApplicationCreateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoanApplicationCreateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullableLoanApplicationCreateDto struct {
	value *LoanApplicationCreateDto
	isSet bool
}

func (v NullableLoanApplicationCreateDto) Get() *LoanApplicationCreateDto {
	return v.value
}

func (v *NullableLoanApplicationCreateDto) Set(val *LoanApplicationCreateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableLoanApplicationCreateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableLoanApplicationCreateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoanApplicationCreateDto(val *LoanApplicationCreateDto) *NullableLoanApplicationCreateDto {
	return &NullableLoanApplicationCreateDto{value: val, isSet: true}
}

func (v NullableLoanApplicationCreateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoanApplicationCreateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


