/*
AccountingService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FiscalYearCreateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FiscalYearCreateDto{}

// FiscalYearCreateDto struct for FiscalYearCreateDto
type FiscalYearCreateDto struct {
	Id *string `json:"id,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Name string `json:"name"`
	Description NullableString `json:"description,omitempty"`
	Closed *bool `json:"closed,omitempty"`
	EndDate *time.Time `json:"endDate,omitempty"`
	StartDate *time.Time `json:"startDate,omitempty"`
	FiscalAuthorityId string `json:"fiscalAuthorityId"`
}

type _FiscalYearCreateDto FiscalYearCreateDto

// NewFiscalYearCreateDto instantiates a new FiscalYearCreateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFiscalYearCreateDto(name string, fiscalAuthorityId string) *FiscalYearCreateDto {
	this := FiscalYearCreateDto{}
	this.Name = name
	this.FiscalAuthorityId = fiscalAuthorityId
	return &this
}

// NewFiscalYearCreateDtoWithDefaults instantiates a new FiscalYearCreateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFiscalYearCreateDtoWithDefaults() *FiscalYearCreateDto {
	this := FiscalYearCreateDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FiscalYearCreateDto) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiscalYearCreateDto) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FiscalYearCreateDto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FiscalYearCreateDto) SetId(v string) {
	o.Id = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *FiscalYearCreateDto) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiscalYearCreateDto) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *FiscalYearCreateDto) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *FiscalYearCreateDto) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetName returns the Name field value
func (o *FiscalYearCreateDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FiscalYearCreateDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FiscalYearCreateDto) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FiscalYearCreateDto) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FiscalYearCreateDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *FiscalYearCreateDto) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *FiscalYearCreateDto) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *FiscalYearCreateDto) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *FiscalYearCreateDto) UnsetDescription() {
	o.Description.Unset()
}

// GetClosed returns the Closed field value if set, zero value otherwise.
func (o *FiscalYearCreateDto) GetClosed() bool {
	if o == nil || IsNil(o.Closed) {
		var ret bool
		return ret
	}
	return *o.Closed
}

// GetClosedOk returns a tuple with the Closed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiscalYearCreateDto) GetClosedOk() (*bool, bool) {
	if o == nil || IsNil(o.Closed) {
		return nil, false
	}
	return o.Closed, true
}

// HasClosed returns a boolean if a field has been set.
func (o *FiscalYearCreateDto) HasClosed() bool {
	if o != nil && !IsNil(o.Closed) {
		return true
	}

	return false
}

// SetClosed gets a reference to the given bool and assigns it to the Closed field.
func (o *FiscalYearCreateDto) SetClosed(v bool) {
	o.Closed = &v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *FiscalYearCreateDto) GetEndDate() time.Time {
	if o == nil || IsNil(o.EndDate) {
		var ret time.Time
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiscalYearCreateDto) GetEndDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *FiscalYearCreateDto) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given time.Time and assigns it to the EndDate field.
func (o *FiscalYearCreateDto) SetEndDate(v time.Time) {
	o.EndDate = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *FiscalYearCreateDto) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiscalYearCreateDto) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *FiscalYearCreateDto) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *FiscalYearCreateDto) SetStartDate(v time.Time) {
	o.StartDate = &v
}

// GetFiscalAuthorityId returns the FiscalAuthorityId field value
func (o *FiscalYearCreateDto) GetFiscalAuthorityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FiscalAuthorityId
}

// GetFiscalAuthorityIdOk returns a tuple with the FiscalAuthorityId field value
// and a boolean to check if the value has been set.
func (o *FiscalYearCreateDto) GetFiscalAuthorityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FiscalAuthorityId, true
}

// SetFiscalAuthorityId sets field value
func (o *FiscalYearCreateDto) SetFiscalAuthorityId(v string) {
	o.FiscalAuthorityId = v
}

func (o FiscalYearCreateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FiscalYearCreateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Closed) {
		toSerialize["closed"] = o.Closed
	}
	if !IsNil(o.EndDate) {
		toSerialize["endDate"] = o.EndDate
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	toSerialize["fiscalAuthorityId"] = o.FiscalAuthorityId
	return toSerialize, nil
}

func (o *FiscalYearCreateDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"fiscalAuthorityId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFiscalYearCreateDto := _FiscalYearCreateDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFiscalYearCreateDto)

	if err != nil {
		return err
	}

	*o = FiscalYearCreateDto(varFiscalYearCreateDto)

	return err
}

type NullableFiscalYearCreateDto struct {
	value *FiscalYearCreateDto
	isSet bool
}

func (v NullableFiscalYearCreateDto) Get() *FiscalYearCreateDto {
	return v.value
}

func (v *NullableFiscalYearCreateDto) Set(val *FiscalYearCreateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableFiscalYearCreateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableFiscalYearCreateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFiscalYearCreateDto(val *FiscalYearCreateDto) *NullableFiscalYearCreateDto {
	return &NullableFiscalYearCreateDto{value: val, isSet: true}
}

func (v NullableFiscalYearCreateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFiscalYearCreateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


