/*
AccountingService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FiscalPeriodUpdateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FiscalPeriodUpdateDto{}

// FiscalPeriodUpdateDto struct for FiscalPeriodUpdateDto
type FiscalPeriodUpdateDto struct {
	Name string `json:"name"`
	FromDate *time.Time `json:"fromDate,omitempty"`
	ToDate *time.Time `json:"toDate,omitempty"`
	FiscalYearId string `json:"fiscalYearId"`
}

type _FiscalPeriodUpdateDto FiscalPeriodUpdateDto

// NewFiscalPeriodUpdateDto instantiates a new FiscalPeriodUpdateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFiscalPeriodUpdateDto(name string, fiscalYearId string) *FiscalPeriodUpdateDto {
	this := FiscalPeriodUpdateDto{}
	this.Name = name
	this.FiscalYearId = fiscalYearId
	return &this
}

// NewFiscalPeriodUpdateDtoWithDefaults instantiates a new FiscalPeriodUpdateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFiscalPeriodUpdateDtoWithDefaults() *FiscalPeriodUpdateDto {
	this := FiscalPeriodUpdateDto{}
	return &this
}

// GetName returns the Name field value
func (o *FiscalPeriodUpdateDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FiscalPeriodUpdateDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FiscalPeriodUpdateDto) SetName(v string) {
	o.Name = v
}

// GetFromDate returns the FromDate field value if set, zero value otherwise.
func (o *FiscalPeriodUpdateDto) GetFromDate() time.Time {
	if o == nil || IsNil(o.FromDate) {
		var ret time.Time
		return ret
	}
	return *o.FromDate
}

// GetFromDateOk returns a tuple with the FromDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiscalPeriodUpdateDto) GetFromDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FromDate) {
		return nil, false
	}
	return o.FromDate, true
}

// HasFromDate returns a boolean if a field has been set.
func (o *FiscalPeriodUpdateDto) HasFromDate() bool {
	if o != nil && !IsNil(o.FromDate) {
		return true
	}

	return false
}

// SetFromDate gets a reference to the given time.Time and assigns it to the FromDate field.
func (o *FiscalPeriodUpdateDto) SetFromDate(v time.Time) {
	o.FromDate = &v
}

// GetToDate returns the ToDate field value if set, zero value otherwise.
func (o *FiscalPeriodUpdateDto) GetToDate() time.Time {
	if o == nil || IsNil(o.ToDate) {
		var ret time.Time
		return ret
	}
	return *o.ToDate
}

// GetToDateOk returns a tuple with the ToDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FiscalPeriodUpdateDto) GetToDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ToDate) {
		return nil, false
	}
	return o.ToDate, true
}

// HasToDate returns a boolean if a field has been set.
func (o *FiscalPeriodUpdateDto) HasToDate() bool {
	if o != nil && !IsNil(o.ToDate) {
		return true
	}

	return false
}

// SetToDate gets a reference to the given time.Time and assigns it to the ToDate field.
func (o *FiscalPeriodUpdateDto) SetToDate(v time.Time) {
	o.ToDate = &v
}

// GetFiscalYearId returns the FiscalYearId field value
func (o *FiscalPeriodUpdateDto) GetFiscalYearId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FiscalYearId
}

// GetFiscalYearIdOk returns a tuple with the FiscalYearId field value
// and a boolean to check if the value has been set.
func (o *FiscalPeriodUpdateDto) GetFiscalYearIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FiscalYearId, true
}

// SetFiscalYearId sets field value
func (o *FiscalPeriodUpdateDto) SetFiscalYearId(v string) {
	o.FiscalYearId = v
}

func (o FiscalPeriodUpdateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FiscalPeriodUpdateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.FromDate) {
		toSerialize["fromDate"] = o.FromDate
	}
	if !IsNil(o.ToDate) {
		toSerialize["toDate"] = o.ToDate
	}
	toSerialize["fiscalYearId"] = o.FiscalYearId
	return toSerialize, nil
}

func (o *FiscalPeriodUpdateDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"fiscalYearId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFiscalPeriodUpdateDto := _FiscalPeriodUpdateDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFiscalPeriodUpdateDto)

	if err != nil {
		return err
	}

	*o = FiscalPeriodUpdateDto(varFiscalPeriodUpdateDto)

	return err
}

type NullableFiscalPeriodUpdateDto struct {
	value *FiscalPeriodUpdateDto
	isSet bool
}

func (v NullableFiscalPeriodUpdateDto) Get() *FiscalPeriodUpdateDto {
	return v.value
}

func (v *NullableFiscalPeriodUpdateDto) Set(val *FiscalPeriodUpdateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableFiscalPeriodUpdateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableFiscalPeriodUpdateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFiscalPeriodUpdateDto(val *FiscalPeriodUpdateDto) *NullableFiscalPeriodUpdateDto {
	return &NullableFiscalPeriodUpdateDto{value: val, isSet: true}
}

func (v NullableFiscalPeriodUpdateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFiscalPeriodUpdateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


