/*
CatalogService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// ItemReviewsAPIService ItemReviewsAPI service
type ItemReviewsAPIService service

type ApiCreateItemReviewAsyncRequest struct {
	ctx context.Context
	ApiService *ItemReviewsAPIService
	tenantId *string
	apiVersion *string
	xApiVersion *string
	itemReviewCreateDto *ItemReviewCreateDto
}

func (r ApiCreateItemReviewAsyncRequest) TenantId(tenantId string) ApiCreateItemReviewAsyncRequest {
	r.tenantId = &tenantId
	return r
}

func (r ApiCreateItemReviewAsyncRequest) ApiVersion(apiVersion string) ApiCreateItemReviewAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiCreateItemReviewAsyncRequest) XApiVersion(xApiVersion string) ApiCreateItemReviewAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiCreateItemReviewAsyncRequest) ItemReviewCreateDto(itemReviewCreateDto ItemReviewCreateDto) ApiCreateItemReviewAsyncRequest {
	r.itemReviewCreateDto = &itemReviewCreateDto
	return r
}

func (r ApiCreateItemReviewAsyncRequest) Execute() (*ItemReviewDtoEnvelope, *http.Response, error) {
	return r.ApiService.CreateItemReviewAsyncExecute(r)
}

/*
CreateItemReviewAsync Create a new item review

Creates a new item review for the specified tenant.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateItemReviewAsyncRequest
*/
func (a *ItemReviewsAPIService) CreateItemReviewAsync(ctx context.Context) ApiCreateItemReviewAsyncRequest {
	return ApiCreateItemReviewAsyncRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ItemReviewDtoEnvelope
func (a *ItemReviewsAPIService) CreateItemReviewAsyncExecute(r ApiCreateItemReviewAsyncRequest) (*ItemReviewDtoEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ItemReviewDtoEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ItemReviewsAPIService.CreateItemReviewAsync")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/CatalogService/ItemReviews"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.tenantId == nil {
		return localVarReturnValue, nil, reportError("tenantId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "tenantId", r.tenantId, "form", "")
	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/xml"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	// body params
	localVarPostBody = r.itemReviewCreateDto
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteItemReviewAsyncRequest struct {
	ctx context.Context
	ApiService *ItemReviewsAPIService
	tenantId *string
	itemReviewId string
	apiVersion *string
	xApiVersion *string
}

func (r ApiDeleteItemReviewAsyncRequest) TenantId(tenantId string) ApiDeleteItemReviewAsyncRequest {
	r.tenantId = &tenantId
	return r
}

func (r ApiDeleteItemReviewAsyncRequest) ApiVersion(apiVersion string) ApiDeleteItemReviewAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiDeleteItemReviewAsyncRequest) XApiVersion(xApiVersion string) ApiDeleteItemReviewAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiDeleteItemReviewAsyncRequest) Execute() (*http.Response, error) {
	return r.ApiService.DeleteItemReviewAsyncExecute(r)
}

/*
DeleteItemReviewAsync Delete an item review

Deletes an item review for the specified tenant.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param itemReviewId
 @return ApiDeleteItemReviewAsyncRequest
*/
func (a *ItemReviewsAPIService) DeleteItemReviewAsync(ctx context.Context, itemReviewId string) ApiDeleteItemReviewAsyncRequest {
	return ApiDeleteItemReviewAsyncRequest{
		ApiService: a,
		ctx: ctx,
		itemReviewId: itemReviewId,
	}
}

// Execute executes the request
func (a *ItemReviewsAPIService) DeleteItemReviewAsyncExecute(r ApiDeleteItemReviewAsyncRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ItemReviewsAPIService.DeleteItemReviewAsync")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/CatalogService/ItemReviews/{itemReviewId}"
	localVarPath = strings.Replace(localVarPath, "{"+"itemReviewId"+"}", url.PathEscape(parameterValueToString(r.itemReviewId, "itemReviewId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.tenantId == nil {
		return nil, reportError("tenantId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "tenantId", r.tenantId, "form", "")
	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiGetItemReviewByIdAsyncRequest struct {
	ctx context.Context
	ApiService *ItemReviewsAPIService
	itemReviewId string
	apiVersion *string
	xApiVersion *string
}

func (r ApiGetItemReviewByIdAsyncRequest) ApiVersion(apiVersion string) ApiGetItemReviewByIdAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiGetItemReviewByIdAsyncRequest) XApiVersion(xApiVersion string) ApiGetItemReviewByIdAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiGetItemReviewByIdAsyncRequest) Execute() (*ItemReviewDtoEnvelope, *http.Response, error) {
	return r.ApiService.GetItemReviewByIdAsyncExecute(r)
}

/*
GetItemReviewByIdAsync Get item review by ID

Retrieves a specific item review by its ID.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param itemReviewId
 @return ApiGetItemReviewByIdAsyncRequest
*/
func (a *ItemReviewsAPIService) GetItemReviewByIdAsync(ctx context.Context, itemReviewId string) ApiGetItemReviewByIdAsyncRequest {
	return ApiGetItemReviewByIdAsyncRequest{
		ApiService: a,
		ctx: ctx,
		itemReviewId: itemReviewId,
	}
}

// Execute executes the request
//  @return ItemReviewDtoEnvelope
func (a *ItemReviewsAPIService) GetItemReviewByIdAsyncExecute(r ApiGetItemReviewByIdAsyncRequest) (*ItemReviewDtoEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ItemReviewDtoEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ItemReviewsAPIService.GetItemReviewByIdAsync")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/CatalogService/ItemReviews/{itemReviewId}"
	localVarPath = strings.Replace(localVarPath, "{"+"itemReviewId"+"}", url.PathEscape(parameterValueToString(r.itemReviewId, "itemReviewId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetItemReviewsAsyncRequest struct {
	ctx context.Context
	ApiService *ItemReviewsAPIService
	itemId *string
	apiVersion *string
	xApiVersion *string
}

func (r ApiGetItemReviewsAsyncRequest) ItemId(itemId string) ApiGetItemReviewsAsyncRequest {
	r.itemId = &itemId
	return r
}

func (r ApiGetItemReviewsAsyncRequest) ApiVersion(apiVersion string) ApiGetItemReviewsAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiGetItemReviewsAsyncRequest) XApiVersion(xApiVersion string) ApiGetItemReviewsAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiGetItemReviewsAsyncRequest) Execute() (*ItemReviewDtoListEnvelope, *http.Response, error) {
	return r.ApiService.GetItemReviewsAsyncExecute(r)
}

/*
GetItemReviewsAsync Get all item reviews

Retrieves all item reviews for the specified item using OData query options.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetItemReviewsAsyncRequest
*/
func (a *ItemReviewsAPIService) GetItemReviewsAsync(ctx context.Context) ApiGetItemReviewsAsyncRequest {
	return ApiGetItemReviewsAsyncRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ItemReviewDtoListEnvelope
func (a *ItemReviewsAPIService) GetItemReviewsAsyncExecute(r ApiGetItemReviewsAsyncRequest) (*ItemReviewDtoListEnvelope, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ItemReviewDtoListEnvelope
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ItemReviewsAPIService.GetItemReviewsAsync")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/CatalogService/ItemReviews"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.itemId == nil {
		return localVarReturnValue, nil, reportError("itemId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "itemId", r.itemId, "form", "")
	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateItemReviewAsyncRequest struct {
	ctx context.Context
	ApiService *ItemReviewsAPIService
	tenantId *string
	itemReviewId string
	apiVersion *string
	xApiVersion *string
	itemReviewUpdateDto *ItemReviewUpdateDto
}

func (r ApiUpdateItemReviewAsyncRequest) TenantId(tenantId string) ApiUpdateItemReviewAsyncRequest {
	r.tenantId = &tenantId
	return r
}

func (r ApiUpdateItemReviewAsyncRequest) ApiVersion(apiVersion string) ApiUpdateItemReviewAsyncRequest {
	r.apiVersion = &apiVersion
	return r
}

func (r ApiUpdateItemReviewAsyncRequest) XApiVersion(xApiVersion string) ApiUpdateItemReviewAsyncRequest {
	r.xApiVersion = &xApiVersion
	return r
}

func (r ApiUpdateItemReviewAsyncRequest) ItemReviewUpdateDto(itemReviewUpdateDto ItemReviewUpdateDto) ApiUpdateItemReviewAsyncRequest {
	r.itemReviewUpdateDto = &itemReviewUpdateDto
	return r
}

func (r ApiUpdateItemReviewAsyncRequest) Execute() (*http.Response, error) {
	return r.ApiService.UpdateItemReviewAsyncExecute(r)
}

/*
UpdateItemReviewAsync Update an item review

Updates an existing item review for the specified tenant.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param itemReviewId
 @return ApiUpdateItemReviewAsyncRequest
*/
func (a *ItemReviewsAPIService) UpdateItemReviewAsync(ctx context.Context, itemReviewId string) ApiUpdateItemReviewAsyncRequest {
	return ApiUpdateItemReviewAsyncRequest{
		ApiService: a,
		ctx: ctx,
		itemReviewId: itemReviewId,
	}
}

// Execute executes the request
func (a *ItemReviewsAPIService) UpdateItemReviewAsyncExecute(r ApiUpdateItemReviewAsyncRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ItemReviewsAPIService.UpdateItemReviewAsync")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v2/CatalogService/ItemReviews/{itemReviewId}"
	localVarPath = strings.Replace(localVarPath, "{"+"itemReviewId"+"}", url.PathEscape(parameterValueToString(r.itemReviewId, "itemReviewId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.tenantId == nil {
		return nil, reportError("tenantId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "tenantId", r.tenantId, "form", "")
	if r.apiVersion != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api-version", r.apiVersion, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "application/xml"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "application/xml"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.xApiVersion != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "x-api-version", r.xApiVersion, "simple", "")
	}
	// body params
	localVarPostBody = r.itemReviewUpdateDto
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v ErrorEnvelope
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
