/*
SocialService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CurriculumExperienceDtoCollectionQueryParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CurriculumExperienceDtoCollectionQueryParameters{}

// CurriculumExperienceDtoCollectionQueryParameters struct for CurriculumExperienceDtoCollectionQueryParameters
type CurriculumExperienceDtoCollectionQueryParameters struct {
	Top NullableInt32 `json:"top,omitempty"`
	Skip NullableInt32 `json:"skip,omitempty"`
	Count *bool `json:"count,omitempty"`
	Filter NullableString `json:"filter,omitempty"`
	OrderBy NullableString `json:"orderBy,omitempty"`
	Search NullableString `json:"search,omitempty"`
	Select NullableString `json:"select,omitempty"`
	Expand NullableString `json:"expand,omitempty"`
	IsEmpty *bool `json:"isEmpty,omitempty"`
}

// NewCurriculumExperienceDtoCollectionQueryParameters instantiates a new CurriculumExperienceDtoCollectionQueryParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCurriculumExperienceDtoCollectionQueryParameters() *CurriculumExperienceDtoCollectionQueryParameters {
	this := CurriculumExperienceDtoCollectionQueryParameters{}
	return &this
}

// NewCurriculumExperienceDtoCollectionQueryParametersWithDefaults instantiates a new CurriculumExperienceDtoCollectionQueryParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCurriculumExperienceDtoCollectionQueryParametersWithDefaults() *CurriculumExperienceDtoCollectionQueryParameters {
	this := CurriculumExperienceDtoCollectionQueryParameters{}
	return &this
}

// GetTop returns the Top field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetTop() int32 {
	if o == nil || IsNil(o.Top.Get()) {
		var ret int32
		return ret
	}
	return *o.Top.Get()
}

// GetTopOk returns a tuple with the Top field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetTopOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Top.Get(), o.Top.IsSet()
}

// HasTop returns a boolean if a field has been set.
func (o *CurriculumExperienceDtoCollectionQueryParameters) HasTop() bool {
	if o != nil && o.Top.IsSet() {
		return true
	}

	return false
}

// SetTop gets a reference to the given NullableInt32 and assigns it to the Top field.
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetTop(v int32) {
	o.Top.Set(&v)
}
// SetTopNil sets the value for Top to be an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetTopNil() {
	o.Top.Set(nil)
}

// UnsetTop ensures that no value is present for Top, not even an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) UnsetTop() {
	o.Top.Unset()
}

// GetSkip returns the Skip field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetSkip() int32 {
	if o == nil || IsNil(o.Skip.Get()) {
		var ret int32
		return ret
	}
	return *o.Skip.Get()
}

// GetSkipOk returns a tuple with the Skip field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetSkipOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Skip.Get(), o.Skip.IsSet()
}

// HasSkip returns a boolean if a field has been set.
func (o *CurriculumExperienceDtoCollectionQueryParameters) HasSkip() bool {
	if o != nil && o.Skip.IsSet() {
		return true
	}

	return false
}

// SetSkip gets a reference to the given NullableInt32 and assigns it to the Skip field.
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetSkip(v int32) {
	o.Skip.Set(&v)
}
// SetSkipNil sets the value for Skip to be an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetSkipNil() {
	o.Skip.Set(nil)
}

// UnsetSkip ensures that no value is present for Skip, not even an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) UnsetSkip() {
	o.Skip.Unset()
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetCount() bool {
	if o == nil || IsNil(o.Count) {
		var ret bool
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetCountOk() (*bool, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *CurriculumExperienceDtoCollectionQueryParameters) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given bool and assigns it to the Count field.
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetCount(v bool) {
	o.Count = &v
}

// GetFilter returns the Filter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetFilter() string {
	if o == nil || IsNil(o.Filter.Get()) {
		var ret string
		return ret
	}
	return *o.Filter.Get()
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetFilterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Filter.Get(), o.Filter.IsSet()
}

// HasFilter returns a boolean if a field has been set.
func (o *CurriculumExperienceDtoCollectionQueryParameters) HasFilter() bool {
	if o != nil && o.Filter.IsSet() {
		return true
	}

	return false
}

// SetFilter gets a reference to the given NullableString and assigns it to the Filter field.
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetFilter(v string) {
	o.Filter.Set(&v)
}
// SetFilterNil sets the value for Filter to be an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetFilterNil() {
	o.Filter.Set(nil)
}

// UnsetFilter ensures that no value is present for Filter, not even an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) UnsetFilter() {
	o.Filter.Unset()
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetOrderBy() string {
	if o == nil || IsNil(o.OrderBy.Get()) {
		var ret string
		return ret
	}
	return *o.OrderBy.Get()
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetOrderByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OrderBy.Get(), o.OrderBy.IsSet()
}

// HasOrderBy returns a boolean if a field has been set.
func (o *CurriculumExperienceDtoCollectionQueryParameters) HasOrderBy() bool {
	if o != nil && o.OrderBy.IsSet() {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given NullableString and assigns it to the OrderBy field.
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetOrderBy(v string) {
	o.OrderBy.Set(&v)
}
// SetOrderByNil sets the value for OrderBy to be an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetOrderByNil() {
	o.OrderBy.Set(nil)
}

// UnsetOrderBy ensures that no value is present for OrderBy, not even an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) UnsetOrderBy() {
	o.OrderBy.Unset()
}

// GetSearch returns the Search field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetSearch() string {
	if o == nil || IsNil(o.Search.Get()) {
		var ret string
		return ret
	}
	return *o.Search.Get()
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetSearchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Search.Get(), o.Search.IsSet()
}

// HasSearch returns a boolean if a field has been set.
func (o *CurriculumExperienceDtoCollectionQueryParameters) HasSearch() bool {
	if o != nil && o.Search.IsSet() {
		return true
	}

	return false
}

// SetSearch gets a reference to the given NullableString and assigns it to the Search field.
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetSearch(v string) {
	o.Search.Set(&v)
}
// SetSearchNil sets the value for Search to be an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetSearchNil() {
	o.Search.Set(nil)
}

// UnsetSearch ensures that no value is present for Search, not even an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) UnsetSearch() {
	o.Search.Unset()
}

// GetSelect returns the Select field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetSelect() string {
	if o == nil || IsNil(o.Select.Get()) {
		var ret string
		return ret
	}
	return *o.Select.Get()
}

// GetSelectOk returns a tuple with the Select field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetSelectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Select.Get(), o.Select.IsSet()
}

// HasSelect returns a boolean if a field has been set.
func (o *CurriculumExperienceDtoCollectionQueryParameters) HasSelect() bool {
	if o != nil && o.Select.IsSet() {
		return true
	}

	return false
}

// SetSelect gets a reference to the given NullableString and assigns it to the Select field.
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetSelect(v string) {
	o.Select.Set(&v)
}
// SetSelectNil sets the value for Select to be an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetSelectNil() {
	o.Select.Set(nil)
}

// UnsetSelect ensures that no value is present for Select, not even an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) UnsetSelect() {
	o.Select.Unset()
}

// GetExpand returns the Expand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetExpand() string {
	if o == nil || IsNil(o.Expand.Get()) {
		var ret string
		return ret
	}
	return *o.Expand.Get()
}

// GetExpandOk returns a tuple with the Expand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetExpandOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Expand.Get(), o.Expand.IsSet()
}

// HasExpand returns a boolean if a field has been set.
func (o *CurriculumExperienceDtoCollectionQueryParameters) HasExpand() bool {
	if o != nil && o.Expand.IsSet() {
		return true
	}

	return false
}

// SetExpand gets a reference to the given NullableString and assigns it to the Expand field.
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetExpand(v string) {
	o.Expand.Set(&v)
}
// SetExpandNil sets the value for Expand to be an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetExpandNil() {
	o.Expand.Set(nil)
}

// UnsetExpand ensures that no value is present for Expand, not even an explicit nil
func (o *CurriculumExperienceDtoCollectionQueryParameters) UnsetExpand() {
	o.Expand.Unset()
}

// GetIsEmpty returns the IsEmpty field value if set, zero value otherwise.
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetIsEmpty() bool {
	if o == nil || IsNil(o.IsEmpty) {
		var ret bool
		return ret
	}
	return *o.IsEmpty
}

// GetIsEmptyOk returns a tuple with the IsEmpty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CurriculumExperienceDtoCollectionQueryParameters) GetIsEmptyOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEmpty) {
		return nil, false
	}
	return o.IsEmpty, true
}

// HasIsEmpty returns a boolean if a field has been set.
func (o *CurriculumExperienceDtoCollectionQueryParameters) HasIsEmpty() bool {
	if o != nil && !IsNil(o.IsEmpty) {
		return true
	}

	return false
}

// SetIsEmpty gets a reference to the given bool and assigns it to the IsEmpty field.
func (o *CurriculumExperienceDtoCollectionQueryParameters) SetIsEmpty(v bool) {
	o.IsEmpty = &v
}

func (o CurriculumExperienceDtoCollectionQueryParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CurriculumExperienceDtoCollectionQueryParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Top.IsSet() {
		toSerialize["top"] = o.Top.Get()
	}
	if o.Skip.IsSet() {
		toSerialize["skip"] = o.Skip.Get()
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if o.Filter.IsSet() {
		toSerialize["filter"] = o.Filter.Get()
	}
	if o.OrderBy.IsSet() {
		toSerialize["orderBy"] = o.OrderBy.Get()
	}
	if o.Search.IsSet() {
		toSerialize["search"] = o.Search.Get()
	}
	if o.Select.IsSet() {
		toSerialize["select"] = o.Select.Get()
	}
	if o.Expand.IsSet() {
		toSerialize["expand"] = o.Expand.Get()
	}
	if !IsNil(o.IsEmpty) {
		toSerialize["isEmpty"] = o.IsEmpty
	}
	return toSerialize, nil
}

type NullableCurriculumExperienceDtoCollectionQueryParameters struct {
	value *CurriculumExperienceDtoCollectionQueryParameters
	isSet bool
}

func (v NullableCurriculumExperienceDtoCollectionQueryParameters) Get() *CurriculumExperienceDtoCollectionQueryParameters {
	return v.value
}

func (v *NullableCurriculumExperienceDtoCollectionQueryParameters) Set(val *CurriculumExperienceDtoCollectionQueryParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableCurriculumExperienceDtoCollectionQueryParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableCurriculumExperienceDtoCollectionQueryParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCurriculumExperienceDtoCollectionQueryParameters(val *CurriculumExperienceDtoCollectionQueryParameters) *NullableCurriculumExperienceDtoCollectionQueryParameters {
	return &NullableCurriculumExperienceDtoCollectionQueryParameters{value: val, isSet: true}
}

func (v NullableCurriculumExperienceDtoCollectionQueryParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCurriculumExperienceDtoCollectionQueryParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


