/*
PricingService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ItemPriceCalculation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemPriceCalculation{}

// ItemPriceCalculation struct for ItemPriceCalculation
type ItemPriceCalculation struct {
	Quantity *float64 `json:"quantity,omitempty"`
	ItemId NullableString `json:"itemId,omitempty"`
	Item NullableString `json:"item,omitempty"`
	UnitId NullableString `json:"unitId,omitempty"`
	UnitGroupId NullableString `json:"unitGroupId,omitempty"`
	PriceId NullableString `json:"priceId,omitempty"`
	PriceListId NullableString `json:"priceListId,omitempty"`
	DiscountId NullableString `json:"discountId,omitempty"`
	DiscountListId NullableString `json:"discountListId,omitempty"`
	TenantId NullableString `json:"tenantId,omitempty"`
	EnrollmentId NullableString `json:"enrollmentId,omitempty"`
	RoundingPolicyId NullableString `json:"roundingPolicyId,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	EffectiveDiscountPercent *float64 `json:"effectiveDiscountPercent,omitempty"`
	EffectiveTaxPercent *float64 `json:"effectiveTaxPercent,omitempty"`
	CurrencyId NullableString `json:"currencyId,omitempty"`
	Currency *CurrencyId `json:"currency,omitempty"`
	TotalBaseAmount *Money `json:"totalBaseAmount,omitempty"`
	TotalProfitAmount *Money `json:"totalProfitAmount,omitempty"`
	TotalDetailAmount *Money `json:"totalDetailAmount,omitempty"`
	TotalDiscountsAmount *Money `json:"totalDiscountsAmount,omitempty"`
	TotalSurchargesAmount *Money `json:"totalSurchargesAmount,omitempty"`
	TotalTaxBaseAmount *Money `json:"totalTaxBaseAmount,omitempty"`
	TotalTaxAmount *Money `json:"totalTaxAmount,omitempty"`
	TotalWTaxAmount *Money `json:"totalWTaxAmount,omitempty"`
	TotalShippingCostAmount *Money `json:"totalShippingCostAmount,omitempty"`
	TotalShippingTaxAmount *Money `json:"totalShippingTaxAmount,omitempty"`
	TotalAmount *Money `json:"totalAmount,omitempty"`
}

// NewItemPriceCalculation instantiates a new ItemPriceCalculation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemPriceCalculation() *ItemPriceCalculation {
	this := ItemPriceCalculation{}
	return &this
}

// NewItemPriceCalculationWithDefaults instantiates a new ItemPriceCalculation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemPriceCalculationWithDefaults() *ItemPriceCalculation {
	this := ItemPriceCalculation{}
	return &this
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetQuantity() float64 {
	if o == nil || IsNil(o.Quantity) {
		var ret float64
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetQuantityOk() (*float64, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float64 and assigns it to the Quantity field.
func (o *ItemPriceCalculation) SetQuantity(v float64) {
	o.Quantity = &v
}

// GetItemId returns the ItemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetItemId() string {
	if o == nil || IsNil(o.ItemId.Get()) {
		var ret string
		return ret
	}
	return *o.ItemId.Get()
}

// GetItemIdOk returns a tuple with the ItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemId.Get(), o.ItemId.IsSet()
}

// HasItemId returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasItemId() bool {
	if o != nil && o.ItemId.IsSet() {
		return true
	}

	return false
}

// SetItemId gets a reference to the given NullableString and assigns it to the ItemId field.
func (o *ItemPriceCalculation) SetItemId(v string) {
	o.ItemId.Set(&v)
}
// SetItemIdNil sets the value for ItemId to be an explicit nil
func (o *ItemPriceCalculation) SetItemIdNil() {
	o.ItemId.Set(nil)
}

// UnsetItemId ensures that no value is present for ItemId, not even an explicit nil
func (o *ItemPriceCalculation) UnsetItemId() {
	o.ItemId.Unset()
}

// GetItem returns the Item field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetItem() string {
	if o == nil || IsNil(o.Item.Get()) {
		var ret string
		return ret
	}
	return *o.Item.Get()
}

// GetItemOk returns a tuple with the Item field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetItemOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Item.Get(), o.Item.IsSet()
}

// HasItem returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasItem() bool {
	if o != nil && o.Item.IsSet() {
		return true
	}

	return false
}

// SetItem gets a reference to the given NullableString and assigns it to the Item field.
func (o *ItemPriceCalculation) SetItem(v string) {
	o.Item.Set(&v)
}
// SetItemNil sets the value for Item to be an explicit nil
func (o *ItemPriceCalculation) SetItemNil() {
	o.Item.Set(nil)
}

// UnsetItem ensures that no value is present for Item, not even an explicit nil
func (o *ItemPriceCalculation) UnsetItem() {
	o.Item.Unset()
}

// GetUnitId returns the UnitId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetUnitId() string {
	if o == nil || IsNil(o.UnitId.Get()) {
		var ret string
		return ret
	}
	return *o.UnitId.Get()
}

// GetUnitIdOk returns a tuple with the UnitId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetUnitIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UnitId.Get(), o.UnitId.IsSet()
}

// HasUnitId returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasUnitId() bool {
	if o != nil && o.UnitId.IsSet() {
		return true
	}

	return false
}

// SetUnitId gets a reference to the given NullableString and assigns it to the UnitId field.
func (o *ItemPriceCalculation) SetUnitId(v string) {
	o.UnitId.Set(&v)
}
// SetUnitIdNil sets the value for UnitId to be an explicit nil
func (o *ItemPriceCalculation) SetUnitIdNil() {
	o.UnitId.Set(nil)
}

// UnsetUnitId ensures that no value is present for UnitId, not even an explicit nil
func (o *ItemPriceCalculation) UnsetUnitId() {
	o.UnitId.Unset()
}

// GetUnitGroupId returns the UnitGroupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetUnitGroupId() string {
	if o == nil || IsNil(o.UnitGroupId.Get()) {
		var ret string
		return ret
	}
	return *o.UnitGroupId.Get()
}

// GetUnitGroupIdOk returns a tuple with the UnitGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetUnitGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UnitGroupId.Get(), o.UnitGroupId.IsSet()
}

// HasUnitGroupId returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasUnitGroupId() bool {
	if o != nil && o.UnitGroupId.IsSet() {
		return true
	}

	return false
}

// SetUnitGroupId gets a reference to the given NullableString and assigns it to the UnitGroupId field.
func (o *ItemPriceCalculation) SetUnitGroupId(v string) {
	o.UnitGroupId.Set(&v)
}
// SetUnitGroupIdNil sets the value for UnitGroupId to be an explicit nil
func (o *ItemPriceCalculation) SetUnitGroupIdNil() {
	o.UnitGroupId.Set(nil)
}

// UnsetUnitGroupId ensures that no value is present for UnitGroupId, not even an explicit nil
func (o *ItemPriceCalculation) UnsetUnitGroupId() {
	o.UnitGroupId.Unset()
}

// GetPriceId returns the PriceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetPriceId() string {
	if o == nil || IsNil(o.PriceId.Get()) {
		var ret string
		return ret
	}
	return *o.PriceId.Get()
}

// GetPriceIdOk returns a tuple with the PriceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetPriceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PriceId.Get(), o.PriceId.IsSet()
}

// HasPriceId returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasPriceId() bool {
	if o != nil && o.PriceId.IsSet() {
		return true
	}

	return false
}

// SetPriceId gets a reference to the given NullableString and assigns it to the PriceId field.
func (o *ItemPriceCalculation) SetPriceId(v string) {
	o.PriceId.Set(&v)
}
// SetPriceIdNil sets the value for PriceId to be an explicit nil
func (o *ItemPriceCalculation) SetPriceIdNil() {
	o.PriceId.Set(nil)
}

// UnsetPriceId ensures that no value is present for PriceId, not even an explicit nil
func (o *ItemPriceCalculation) UnsetPriceId() {
	o.PriceId.Unset()
}

// GetPriceListId returns the PriceListId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetPriceListId() string {
	if o == nil || IsNil(o.PriceListId.Get()) {
		var ret string
		return ret
	}
	return *o.PriceListId.Get()
}

// GetPriceListIdOk returns a tuple with the PriceListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetPriceListIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PriceListId.Get(), o.PriceListId.IsSet()
}

// HasPriceListId returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasPriceListId() bool {
	if o != nil && o.PriceListId.IsSet() {
		return true
	}

	return false
}

// SetPriceListId gets a reference to the given NullableString and assigns it to the PriceListId field.
func (o *ItemPriceCalculation) SetPriceListId(v string) {
	o.PriceListId.Set(&v)
}
// SetPriceListIdNil sets the value for PriceListId to be an explicit nil
func (o *ItemPriceCalculation) SetPriceListIdNil() {
	o.PriceListId.Set(nil)
}

// UnsetPriceListId ensures that no value is present for PriceListId, not even an explicit nil
func (o *ItemPriceCalculation) UnsetPriceListId() {
	o.PriceListId.Unset()
}

// GetDiscountId returns the DiscountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetDiscountId() string {
	if o == nil || IsNil(o.DiscountId.Get()) {
		var ret string
		return ret
	}
	return *o.DiscountId.Get()
}

// GetDiscountIdOk returns a tuple with the DiscountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetDiscountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiscountId.Get(), o.DiscountId.IsSet()
}

// HasDiscountId returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasDiscountId() bool {
	if o != nil && o.DiscountId.IsSet() {
		return true
	}

	return false
}

// SetDiscountId gets a reference to the given NullableString and assigns it to the DiscountId field.
func (o *ItemPriceCalculation) SetDiscountId(v string) {
	o.DiscountId.Set(&v)
}
// SetDiscountIdNil sets the value for DiscountId to be an explicit nil
func (o *ItemPriceCalculation) SetDiscountIdNil() {
	o.DiscountId.Set(nil)
}

// UnsetDiscountId ensures that no value is present for DiscountId, not even an explicit nil
func (o *ItemPriceCalculation) UnsetDiscountId() {
	o.DiscountId.Unset()
}

// GetDiscountListId returns the DiscountListId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetDiscountListId() string {
	if o == nil || IsNil(o.DiscountListId.Get()) {
		var ret string
		return ret
	}
	return *o.DiscountListId.Get()
}

// GetDiscountListIdOk returns a tuple with the DiscountListId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetDiscountListIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiscountListId.Get(), o.DiscountListId.IsSet()
}

// HasDiscountListId returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasDiscountListId() bool {
	if o != nil && o.DiscountListId.IsSet() {
		return true
	}

	return false
}

// SetDiscountListId gets a reference to the given NullableString and assigns it to the DiscountListId field.
func (o *ItemPriceCalculation) SetDiscountListId(v string) {
	o.DiscountListId.Set(&v)
}
// SetDiscountListIdNil sets the value for DiscountListId to be an explicit nil
func (o *ItemPriceCalculation) SetDiscountListIdNil() {
	o.DiscountListId.Set(nil)
}

// UnsetDiscountListId ensures that no value is present for DiscountListId, not even an explicit nil
func (o *ItemPriceCalculation) UnsetDiscountListId() {
	o.DiscountListId.Unset()
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *ItemPriceCalculation) SetTenantId(v string) {
	o.TenantId.Set(&v)
}
// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *ItemPriceCalculation) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *ItemPriceCalculation) UnsetTenantId() {
	o.TenantId.Unset()
}

// GetEnrollmentId returns the EnrollmentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetEnrollmentId() string {
	if o == nil || IsNil(o.EnrollmentId.Get()) {
		var ret string
		return ret
	}
	return *o.EnrollmentId.Get()
}

// GetEnrollmentIdOk returns a tuple with the EnrollmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetEnrollmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnrollmentId.Get(), o.EnrollmentId.IsSet()
}

// HasEnrollmentId returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasEnrollmentId() bool {
	if o != nil && o.EnrollmentId.IsSet() {
		return true
	}

	return false
}

// SetEnrollmentId gets a reference to the given NullableString and assigns it to the EnrollmentId field.
func (o *ItemPriceCalculation) SetEnrollmentId(v string) {
	o.EnrollmentId.Set(&v)
}
// SetEnrollmentIdNil sets the value for EnrollmentId to be an explicit nil
func (o *ItemPriceCalculation) SetEnrollmentIdNil() {
	o.EnrollmentId.Set(nil)
}

// UnsetEnrollmentId ensures that no value is present for EnrollmentId, not even an explicit nil
func (o *ItemPriceCalculation) UnsetEnrollmentId() {
	o.EnrollmentId.Unset()
}

// GetRoundingPolicyId returns the RoundingPolicyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetRoundingPolicyId() string {
	if o == nil || IsNil(o.RoundingPolicyId.Get()) {
		var ret string
		return ret
	}
	return *o.RoundingPolicyId.Get()
}

// GetRoundingPolicyIdOk returns a tuple with the RoundingPolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetRoundingPolicyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoundingPolicyId.Get(), o.RoundingPolicyId.IsSet()
}

// HasRoundingPolicyId returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasRoundingPolicyId() bool {
	if o != nil && o.RoundingPolicyId.IsSet() {
		return true
	}

	return false
}

// SetRoundingPolicyId gets a reference to the given NullableString and assigns it to the RoundingPolicyId field.
func (o *ItemPriceCalculation) SetRoundingPolicyId(v string) {
	o.RoundingPolicyId.Set(&v)
}
// SetRoundingPolicyIdNil sets the value for RoundingPolicyId to be an explicit nil
func (o *ItemPriceCalculation) SetRoundingPolicyIdNil() {
	o.RoundingPolicyId.Set(nil)
}

// UnsetRoundingPolicyId ensures that no value is present for RoundingPolicyId, not even an explicit nil
func (o *ItemPriceCalculation) UnsetRoundingPolicyId() {
	o.RoundingPolicyId.Unset()
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *ItemPriceCalculation) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetEffectiveDiscountPercent returns the EffectiveDiscountPercent field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetEffectiveDiscountPercent() float64 {
	if o == nil || IsNil(o.EffectiveDiscountPercent) {
		var ret float64
		return ret
	}
	return *o.EffectiveDiscountPercent
}

// GetEffectiveDiscountPercentOk returns a tuple with the EffectiveDiscountPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetEffectiveDiscountPercentOk() (*float64, bool) {
	if o == nil || IsNil(o.EffectiveDiscountPercent) {
		return nil, false
	}
	return o.EffectiveDiscountPercent, true
}

// HasEffectiveDiscountPercent returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasEffectiveDiscountPercent() bool {
	if o != nil && !IsNil(o.EffectiveDiscountPercent) {
		return true
	}

	return false
}

// SetEffectiveDiscountPercent gets a reference to the given float64 and assigns it to the EffectiveDiscountPercent field.
func (o *ItemPriceCalculation) SetEffectiveDiscountPercent(v float64) {
	o.EffectiveDiscountPercent = &v
}

// GetEffectiveTaxPercent returns the EffectiveTaxPercent field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetEffectiveTaxPercent() float64 {
	if o == nil || IsNil(o.EffectiveTaxPercent) {
		var ret float64
		return ret
	}
	return *o.EffectiveTaxPercent
}

// GetEffectiveTaxPercentOk returns a tuple with the EffectiveTaxPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetEffectiveTaxPercentOk() (*float64, bool) {
	if o == nil || IsNil(o.EffectiveTaxPercent) {
		return nil, false
	}
	return o.EffectiveTaxPercent, true
}

// HasEffectiveTaxPercent returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasEffectiveTaxPercent() bool {
	if o != nil && !IsNil(o.EffectiveTaxPercent) {
		return true
	}

	return false
}

// SetEffectiveTaxPercent gets a reference to the given float64 and assigns it to the EffectiveTaxPercent field.
func (o *ItemPriceCalculation) SetEffectiveTaxPercent(v float64) {
	o.EffectiveTaxPercent = &v
}

// GetCurrencyId returns the CurrencyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemPriceCalculation) GetCurrencyId() string {
	if o == nil || IsNil(o.CurrencyId.Get()) {
		var ret string
		return ret
	}
	return *o.CurrencyId.Get()
}

// GetCurrencyIdOk returns a tuple with the CurrencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemPriceCalculation) GetCurrencyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrencyId.Get(), o.CurrencyId.IsSet()
}

// HasCurrencyId returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasCurrencyId() bool {
	if o != nil && o.CurrencyId.IsSet() {
		return true
	}

	return false
}

// SetCurrencyId gets a reference to the given NullableString and assigns it to the CurrencyId field.
func (o *ItemPriceCalculation) SetCurrencyId(v string) {
	o.CurrencyId.Set(&v)
}
// SetCurrencyIdNil sets the value for CurrencyId to be an explicit nil
func (o *ItemPriceCalculation) SetCurrencyIdNil() {
	o.CurrencyId.Set(nil)
}

// UnsetCurrencyId ensures that no value is present for CurrencyId, not even an explicit nil
func (o *ItemPriceCalculation) UnsetCurrencyId() {
	o.CurrencyId.Unset()
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetCurrency() CurrencyId {
	if o == nil || IsNil(o.Currency) {
		var ret CurrencyId
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetCurrencyOk() (*CurrencyId, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given CurrencyId and assigns it to the Currency field.
func (o *ItemPriceCalculation) SetCurrency(v CurrencyId) {
	o.Currency = &v
}

// GetTotalBaseAmount returns the TotalBaseAmount field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTotalBaseAmount() Money {
	if o == nil || IsNil(o.TotalBaseAmount) {
		var ret Money
		return ret
	}
	return *o.TotalBaseAmount
}

// GetTotalBaseAmountOk returns a tuple with the TotalBaseAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTotalBaseAmountOk() (*Money, bool) {
	if o == nil || IsNil(o.TotalBaseAmount) {
		return nil, false
	}
	return o.TotalBaseAmount, true
}

// HasTotalBaseAmount returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTotalBaseAmount() bool {
	if o != nil && !IsNil(o.TotalBaseAmount) {
		return true
	}

	return false
}

// SetTotalBaseAmount gets a reference to the given Money and assigns it to the TotalBaseAmount field.
func (o *ItemPriceCalculation) SetTotalBaseAmount(v Money) {
	o.TotalBaseAmount = &v
}

// GetTotalProfitAmount returns the TotalProfitAmount field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTotalProfitAmount() Money {
	if o == nil || IsNil(o.TotalProfitAmount) {
		var ret Money
		return ret
	}
	return *o.TotalProfitAmount
}

// GetTotalProfitAmountOk returns a tuple with the TotalProfitAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTotalProfitAmountOk() (*Money, bool) {
	if o == nil || IsNil(o.TotalProfitAmount) {
		return nil, false
	}
	return o.TotalProfitAmount, true
}

// HasTotalProfitAmount returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTotalProfitAmount() bool {
	if o != nil && !IsNil(o.TotalProfitAmount) {
		return true
	}

	return false
}

// SetTotalProfitAmount gets a reference to the given Money and assigns it to the TotalProfitAmount field.
func (o *ItemPriceCalculation) SetTotalProfitAmount(v Money) {
	o.TotalProfitAmount = &v
}

// GetTotalDetailAmount returns the TotalDetailAmount field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTotalDetailAmount() Money {
	if o == nil || IsNil(o.TotalDetailAmount) {
		var ret Money
		return ret
	}
	return *o.TotalDetailAmount
}

// GetTotalDetailAmountOk returns a tuple with the TotalDetailAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTotalDetailAmountOk() (*Money, bool) {
	if o == nil || IsNil(o.TotalDetailAmount) {
		return nil, false
	}
	return o.TotalDetailAmount, true
}

// HasTotalDetailAmount returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTotalDetailAmount() bool {
	if o != nil && !IsNil(o.TotalDetailAmount) {
		return true
	}

	return false
}

// SetTotalDetailAmount gets a reference to the given Money and assigns it to the TotalDetailAmount field.
func (o *ItemPriceCalculation) SetTotalDetailAmount(v Money) {
	o.TotalDetailAmount = &v
}

// GetTotalDiscountsAmount returns the TotalDiscountsAmount field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTotalDiscountsAmount() Money {
	if o == nil || IsNil(o.TotalDiscountsAmount) {
		var ret Money
		return ret
	}
	return *o.TotalDiscountsAmount
}

// GetTotalDiscountsAmountOk returns a tuple with the TotalDiscountsAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTotalDiscountsAmountOk() (*Money, bool) {
	if o == nil || IsNil(o.TotalDiscountsAmount) {
		return nil, false
	}
	return o.TotalDiscountsAmount, true
}

// HasTotalDiscountsAmount returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTotalDiscountsAmount() bool {
	if o != nil && !IsNil(o.TotalDiscountsAmount) {
		return true
	}

	return false
}

// SetTotalDiscountsAmount gets a reference to the given Money and assigns it to the TotalDiscountsAmount field.
func (o *ItemPriceCalculation) SetTotalDiscountsAmount(v Money) {
	o.TotalDiscountsAmount = &v
}

// GetTotalSurchargesAmount returns the TotalSurchargesAmount field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTotalSurchargesAmount() Money {
	if o == nil || IsNil(o.TotalSurchargesAmount) {
		var ret Money
		return ret
	}
	return *o.TotalSurchargesAmount
}

// GetTotalSurchargesAmountOk returns a tuple with the TotalSurchargesAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTotalSurchargesAmountOk() (*Money, bool) {
	if o == nil || IsNil(o.TotalSurchargesAmount) {
		return nil, false
	}
	return o.TotalSurchargesAmount, true
}

// HasTotalSurchargesAmount returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTotalSurchargesAmount() bool {
	if o != nil && !IsNil(o.TotalSurchargesAmount) {
		return true
	}

	return false
}

// SetTotalSurchargesAmount gets a reference to the given Money and assigns it to the TotalSurchargesAmount field.
func (o *ItemPriceCalculation) SetTotalSurchargesAmount(v Money) {
	o.TotalSurchargesAmount = &v
}

// GetTotalTaxBaseAmount returns the TotalTaxBaseAmount field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTotalTaxBaseAmount() Money {
	if o == nil || IsNil(o.TotalTaxBaseAmount) {
		var ret Money
		return ret
	}
	return *o.TotalTaxBaseAmount
}

// GetTotalTaxBaseAmountOk returns a tuple with the TotalTaxBaseAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTotalTaxBaseAmountOk() (*Money, bool) {
	if o == nil || IsNil(o.TotalTaxBaseAmount) {
		return nil, false
	}
	return o.TotalTaxBaseAmount, true
}

// HasTotalTaxBaseAmount returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTotalTaxBaseAmount() bool {
	if o != nil && !IsNil(o.TotalTaxBaseAmount) {
		return true
	}

	return false
}

// SetTotalTaxBaseAmount gets a reference to the given Money and assigns it to the TotalTaxBaseAmount field.
func (o *ItemPriceCalculation) SetTotalTaxBaseAmount(v Money) {
	o.TotalTaxBaseAmount = &v
}

// GetTotalTaxAmount returns the TotalTaxAmount field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTotalTaxAmount() Money {
	if o == nil || IsNil(o.TotalTaxAmount) {
		var ret Money
		return ret
	}
	return *o.TotalTaxAmount
}

// GetTotalTaxAmountOk returns a tuple with the TotalTaxAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTotalTaxAmountOk() (*Money, bool) {
	if o == nil || IsNil(o.TotalTaxAmount) {
		return nil, false
	}
	return o.TotalTaxAmount, true
}

// HasTotalTaxAmount returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTotalTaxAmount() bool {
	if o != nil && !IsNil(o.TotalTaxAmount) {
		return true
	}

	return false
}

// SetTotalTaxAmount gets a reference to the given Money and assigns it to the TotalTaxAmount field.
func (o *ItemPriceCalculation) SetTotalTaxAmount(v Money) {
	o.TotalTaxAmount = &v
}

// GetTotalWTaxAmount returns the TotalWTaxAmount field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTotalWTaxAmount() Money {
	if o == nil || IsNil(o.TotalWTaxAmount) {
		var ret Money
		return ret
	}
	return *o.TotalWTaxAmount
}

// GetTotalWTaxAmountOk returns a tuple with the TotalWTaxAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTotalWTaxAmountOk() (*Money, bool) {
	if o == nil || IsNil(o.TotalWTaxAmount) {
		return nil, false
	}
	return o.TotalWTaxAmount, true
}

// HasTotalWTaxAmount returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTotalWTaxAmount() bool {
	if o != nil && !IsNil(o.TotalWTaxAmount) {
		return true
	}

	return false
}

// SetTotalWTaxAmount gets a reference to the given Money and assigns it to the TotalWTaxAmount field.
func (o *ItemPriceCalculation) SetTotalWTaxAmount(v Money) {
	o.TotalWTaxAmount = &v
}

// GetTotalShippingCostAmount returns the TotalShippingCostAmount field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTotalShippingCostAmount() Money {
	if o == nil || IsNil(o.TotalShippingCostAmount) {
		var ret Money
		return ret
	}
	return *o.TotalShippingCostAmount
}

// GetTotalShippingCostAmountOk returns a tuple with the TotalShippingCostAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTotalShippingCostAmountOk() (*Money, bool) {
	if o == nil || IsNil(o.TotalShippingCostAmount) {
		return nil, false
	}
	return o.TotalShippingCostAmount, true
}

// HasTotalShippingCostAmount returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTotalShippingCostAmount() bool {
	if o != nil && !IsNil(o.TotalShippingCostAmount) {
		return true
	}

	return false
}

// SetTotalShippingCostAmount gets a reference to the given Money and assigns it to the TotalShippingCostAmount field.
func (o *ItemPriceCalculation) SetTotalShippingCostAmount(v Money) {
	o.TotalShippingCostAmount = &v
}

// GetTotalShippingTaxAmount returns the TotalShippingTaxAmount field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTotalShippingTaxAmount() Money {
	if o == nil || IsNil(o.TotalShippingTaxAmount) {
		var ret Money
		return ret
	}
	return *o.TotalShippingTaxAmount
}

// GetTotalShippingTaxAmountOk returns a tuple with the TotalShippingTaxAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTotalShippingTaxAmountOk() (*Money, bool) {
	if o == nil || IsNil(o.TotalShippingTaxAmount) {
		return nil, false
	}
	return o.TotalShippingTaxAmount, true
}

// HasTotalShippingTaxAmount returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTotalShippingTaxAmount() bool {
	if o != nil && !IsNil(o.TotalShippingTaxAmount) {
		return true
	}

	return false
}

// SetTotalShippingTaxAmount gets a reference to the given Money and assigns it to the TotalShippingTaxAmount field.
func (o *ItemPriceCalculation) SetTotalShippingTaxAmount(v Money) {
	o.TotalShippingTaxAmount = &v
}

// GetTotalAmount returns the TotalAmount field value if set, zero value otherwise.
func (o *ItemPriceCalculation) GetTotalAmount() Money {
	if o == nil || IsNil(o.TotalAmount) {
		var ret Money
		return ret
	}
	return *o.TotalAmount
}

// GetTotalAmountOk returns a tuple with the TotalAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemPriceCalculation) GetTotalAmountOk() (*Money, bool) {
	if o == nil || IsNil(o.TotalAmount) {
		return nil, false
	}
	return o.TotalAmount, true
}

// HasTotalAmount returns a boolean if a field has been set.
func (o *ItemPriceCalculation) HasTotalAmount() bool {
	if o != nil && !IsNil(o.TotalAmount) {
		return true
	}

	return false
}

// SetTotalAmount gets a reference to the given Money and assigns it to the TotalAmount field.
func (o *ItemPriceCalculation) SetTotalAmount(v Money) {
	o.TotalAmount = &v
}

func (o ItemPriceCalculation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemPriceCalculation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if o.ItemId.IsSet() {
		toSerialize["itemId"] = o.ItemId.Get()
	}
	if o.Item.IsSet() {
		toSerialize["item"] = o.Item.Get()
	}
	if o.UnitId.IsSet() {
		toSerialize["unitId"] = o.UnitId.Get()
	}
	if o.UnitGroupId.IsSet() {
		toSerialize["unitGroupId"] = o.UnitGroupId.Get()
	}
	if o.PriceId.IsSet() {
		toSerialize["priceId"] = o.PriceId.Get()
	}
	if o.PriceListId.IsSet() {
		toSerialize["priceListId"] = o.PriceListId.Get()
	}
	if o.DiscountId.IsSet() {
		toSerialize["discountId"] = o.DiscountId.Get()
	}
	if o.DiscountListId.IsSet() {
		toSerialize["discountListId"] = o.DiscountListId.Get()
	}
	if o.TenantId.IsSet() {
		toSerialize["tenantId"] = o.TenantId.Get()
	}
	if o.EnrollmentId.IsSet() {
		toSerialize["enrollmentId"] = o.EnrollmentId.Get()
	}
	if o.RoundingPolicyId.IsSet() {
		toSerialize["roundingPolicyId"] = o.RoundingPolicyId.Get()
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.EffectiveDiscountPercent) {
		toSerialize["effectiveDiscountPercent"] = o.EffectiveDiscountPercent
	}
	if !IsNil(o.EffectiveTaxPercent) {
		toSerialize["effectiveTaxPercent"] = o.EffectiveTaxPercent
	}
	if o.CurrencyId.IsSet() {
		toSerialize["currencyId"] = o.CurrencyId.Get()
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.TotalBaseAmount) {
		toSerialize["totalBaseAmount"] = o.TotalBaseAmount
	}
	if !IsNil(o.TotalProfitAmount) {
		toSerialize["totalProfitAmount"] = o.TotalProfitAmount
	}
	if !IsNil(o.TotalDetailAmount) {
		toSerialize["totalDetailAmount"] = o.TotalDetailAmount
	}
	if !IsNil(o.TotalDiscountsAmount) {
		toSerialize["totalDiscountsAmount"] = o.TotalDiscountsAmount
	}
	if !IsNil(o.TotalSurchargesAmount) {
		toSerialize["totalSurchargesAmount"] = o.TotalSurchargesAmount
	}
	if !IsNil(o.TotalTaxBaseAmount) {
		toSerialize["totalTaxBaseAmount"] = o.TotalTaxBaseAmount
	}
	if !IsNil(o.TotalTaxAmount) {
		toSerialize["totalTaxAmount"] = o.TotalTaxAmount
	}
	if !IsNil(o.TotalWTaxAmount) {
		toSerialize["totalWTaxAmount"] = o.TotalWTaxAmount
	}
	if !IsNil(o.TotalShippingCostAmount) {
		toSerialize["totalShippingCostAmount"] = o.TotalShippingCostAmount
	}
	if !IsNil(o.TotalShippingTaxAmount) {
		toSerialize["totalShippingTaxAmount"] = o.TotalShippingTaxAmount
	}
	if !IsNil(o.TotalAmount) {
		toSerialize["totalAmount"] = o.TotalAmount
	}
	return toSerialize, nil
}

type NullableItemPriceCalculation struct {
	value *ItemPriceCalculation
	isSet bool
}

func (v NullableItemPriceCalculation) Get() *ItemPriceCalculation {
	return v.value
}

func (v *NullableItemPriceCalculation) Set(val *ItemPriceCalculation) {
	v.value = val
	v.isSet = true
}

func (v NullableItemPriceCalculation) IsSet() bool {
	return v.isSet
}

func (v *NullableItemPriceCalculation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemPriceCalculation(val *ItemPriceCalculation) *NullableItemPriceCalculation {
	return &NullableItemPriceCalculation{value: val, isSet: true}
}

func (v NullableItemPriceCalculation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemPriceCalculation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


