/*
CartService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the ItemToCompareCartRecordDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ItemToCompareCartRecordDto{}

// ItemToCompareCartRecordDto struct for ItemToCompareCartRecordDto
type ItemToCompareCartRecordDto struct {
	Id NullableString `json:"id,omitempty"`
	Timestamp NullableTime `json:"timestamp,omitempty"`
	CartId NullableString `json:"cartId,omitempty"`
	ItemId NullableString `json:"itemId,omitempty"`
	ItemTitle NullableString `json:"itemTitle,omitempty"`
	ItemShortDescription NullableString `json:"itemShortDescription,omitempty"`
	ItemPrimaryImageUrl NullableString `json:"itemPrimaryImageUrl,omitempty"`
	BrandId NullableString `json:"brandId,omitempty"`
	BrandName NullableString `json:"brandName,omitempty"`
	CategoryName NullableString `json:"categoryName,omitempty"`
	CategoryId NullableString `json:"categoryId,omitempty"`
	GoogleCategoryId NullableString `json:"googleCategoryId,omitempty"`
	GoogleCategoryName NullableString `json:"googleCategoryName,omitempty"`
	TotalTaxesInUsd *float64 `json:"totalTaxesInUsd,omitempty"`
	TotalPriceInUsd *float64 `json:"totalPriceInUsd,omitempty"`
	ShippingCountryId NullableString `json:"shippingCountryId,omitempty"`
	TenantId NullableString `json:"tenantId,omitempty"`
}

// NewItemToCompareCartRecordDto instantiates a new ItemToCompareCartRecordDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewItemToCompareCartRecordDto() *ItemToCompareCartRecordDto {
	this := ItemToCompareCartRecordDto{}
	return &this
}

// NewItemToCompareCartRecordDtoWithDefaults instantiates a new ItemToCompareCartRecordDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewItemToCompareCartRecordDtoWithDefaults() *ItemToCompareCartRecordDto {
	this := ItemToCompareCartRecordDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ItemToCompareCartRecordDto) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetId() {
	o.Id.Unset()
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableTime and assigns it to the Timestamp field.
func (o *ItemToCompareCartRecordDto) SetTimestamp(v time.Time) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetCartId returns the CartId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetCartId() string {
	if o == nil || IsNil(o.CartId.Get()) {
		var ret string
		return ret
	}
	return *o.CartId.Get()
}

// GetCartIdOk returns a tuple with the CartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetCartIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CartId.Get(), o.CartId.IsSet()
}

// HasCartId returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasCartId() bool {
	if o != nil && o.CartId.IsSet() {
		return true
	}

	return false
}

// SetCartId gets a reference to the given NullableString and assigns it to the CartId field.
func (o *ItemToCompareCartRecordDto) SetCartId(v string) {
	o.CartId.Set(&v)
}
// SetCartIdNil sets the value for CartId to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetCartIdNil() {
	o.CartId.Set(nil)
}

// UnsetCartId ensures that no value is present for CartId, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetCartId() {
	o.CartId.Unset()
}

// GetItemId returns the ItemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetItemId() string {
	if o == nil || IsNil(o.ItemId.Get()) {
		var ret string
		return ret
	}
	return *o.ItemId.Get()
}

// GetItemIdOk returns a tuple with the ItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemId.Get(), o.ItemId.IsSet()
}

// HasItemId returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasItemId() bool {
	if o != nil && o.ItemId.IsSet() {
		return true
	}

	return false
}

// SetItemId gets a reference to the given NullableString and assigns it to the ItemId field.
func (o *ItemToCompareCartRecordDto) SetItemId(v string) {
	o.ItemId.Set(&v)
}
// SetItemIdNil sets the value for ItemId to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetItemIdNil() {
	o.ItemId.Set(nil)
}

// UnsetItemId ensures that no value is present for ItemId, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetItemId() {
	o.ItemId.Unset()
}

// GetItemTitle returns the ItemTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetItemTitle() string {
	if o == nil || IsNil(o.ItemTitle.Get()) {
		var ret string
		return ret
	}
	return *o.ItemTitle.Get()
}

// GetItemTitleOk returns a tuple with the ItemTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetItemTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemTitle.Get(), o.ItemTitle.IsSet()
}

// HasItemTitle returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasItemTitle() bool {
	if o != nil && o.ItemTitle.IsSet() {
		return true
	}

	return false
}

// SetItemTitle gets a reference to the given NullableString and assigns it to the ItemTitle field.
func (o *ItemToCompareCartRecordDto) SetItemTitle(v string) {
	o.ItemTitle.Set(&v)
}
// SetItemTitleNil sets the value for ItemTitle to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetItemTitleNil() {
	o.ItemTitle.Set(nil)
}

// UnsetItemTitle ensures that no value is present for ItemTitle, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetItemTitle() {
	o.ItemTitle.Unset()
}

// GetItemShortDescription returns the ItemShortDescription field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetItemShortDescription() string {
	if o == nil || IsNil(o.ItemShortDescription.Get()) {
		var ret string
		return ret
	}
	return *o.ItemShortDescription.Get()
}

// GetItemShortDescriptionOk returns a tuple with the ItemShortDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetItemShortDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemShortDescription.Get(), o.ItemShortDescription.IsSet()
}

// HasItemShortDescription returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasItemShortDescription() bool {
	if o != nil && o.ItemShortDescription.IsSet() {
		return true
	}

	return false
}

// SetItemShortDescription gets a reference to the given NullableString and assigns it to the ItemShortDescription field.
func (o *ItemToCompareCartRecordDto) SetItemShortDescription(v string) {
	o.ItemShortDescription.Set(&v)
}
// SetItemShortDescriptionNil sets the value for ItemShortDescription to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetItemShortDescriptionNil() {
	o.ItemShortDescription.Set(nil)
}

// UnsetItemShortDescription ensures that no value is present for ItemShortDescription, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetItemShortDescription() {
	o.ItemShortDescription.Unset()
}

// GetItemPrimaryImageUrl returns the ItemPrimaryImageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetItemPrimaryImageUrl() string {
	if o == nil || IsNil(o.ItemPrimaryImageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ItemPrimaryImageUrl.Get()
}

// GetItemPrimaryImageUrlOk returns a tuple with the ItemPrimaryImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetItemPrimaryImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemPrimaryImageUrl.Get(), o.ItemPrimaryImageUrl.IsSet()
}

// HasItemPrimaryImageUrl returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasItemPrimaryImageUrl() bool {
	if o != nil && o.ItemPrimaryImageUrl.IsSet() {
		return true
	}

	return false
}

// SetItemPrimaryImageUrl gets a reference to the given NullableString and assigns it to the ItemPrimaryImageUrl field.
func (o *ItemToCompareCartRecordDto) SetItemPrimaryImageUrl(v string) {
	o.ItemPrimaryImageUrl.Set(&v)
}
// SetItemPrimaryImageUrlNil sets the value for ItemPrimaryImageUrl to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetItemPrimaryImageUrlNil() {
	o.ItemPrimaryImageUrl.Set(nil)
}

// UnsetItemPrimaryImageUrl ensures that no value is present for ItemPrimaryImageUrl, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetItemPrimaryImageUrl() {
	o.ItemPrimaryImageUrl.Unset()
}

// GetBrandId returns the BrandId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetBrandId() string {
	if o == nil || IsNil(o.BrandId.Get()) {
		var ret string
		return ret
	}
	return *o.BrandId.Get()
}

// GetBrandIdOk returns a tuple with the BrandId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetBrandIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BrandId.Get(), o.BrandId.IsSet()
}

// HasBrandId returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasBrandId() bool {
	if o != nil && o.BrandId.IsSet() {
		return true
	}

	return false
}

// SetBrandId gets a reference to the given NullableString and assigns it to the BrandId field.
func (o *ItemToCompareCartRecordDto) SetBrandId(v string) {
	o.BrandId.Set(&v)
}
// SetBrandIdNil sets the value for BrandId to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetBrandIdNil() {
	o.BrandId.Set(nil)
}

// UnsetBrandId ensures that no value is present for BrandId, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetBrandId() {
	o.BrandId.Unset()
}

// GetBrandName returns the BrandName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetBrandName() string {
	if o == nil || IsNil(o.BrandName.Get()) {
		var ret string
		return ret
	}
	return *o.BrandName.Get()
}

// GetBrandNameOk returns a tuple with the BrandName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetBrandNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BrandName.Get(), o.BrandName.IsSet()
}

// HasBrandName returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasBrandName() bool {
	if o != nil && o.BrandName.IsSet() {
		return true
	}

	return false
}

// SetBrandName gets a reference to the given NullableString and assigns it to the BrandName field.
func (o *ItemToCompareCartRecordDto) SetBrandName(v string) {
	o.BrandName.Set(&v)
}
// SetBrandNameNil sets the value for BrandName to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetBrandNameNil() {
	o.BrandName.Set(nil)
}

// UnsetBrandName ensures that no value is present for BrandName, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetBrandName() {
	o.BrandName.Unset()
}

// GetCategoryName returns the CategoryName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetCategoryName() string {
	if o == nil || IsNil(o.CategoryName.Get()) {
		var ret string
		return ret
	}
	return *o.CategoryName.Get()
}

// GetCategoryNameOk returns a tuple with the CategoryName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetCategoryNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CategoryName.Get(), o.CategoryName.IsSet()
}

// HasCategoryName returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasCategoryName() bool {
	if o != nil && o.CategoryName.IsSet() {
		return true
	}

	return false
}

// SetCategoryName gets a reference to the given NullableString and assigns it to the CategoryName field.
func (o *ItemToCompareCartRecordDto) SetCategoryName(v string) {
	o.CategoryName.Set(&v)
}
// SetCategoryNameNil sets the value for CategoryName to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetCategoryNameNil() {
	o.CategoryName.Set(nil)
}

// UnsetCategoryName ensures that no value is present for CategoryName, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetCategoryName() {
	o.CategoryName.Unset()
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetCategoryId() string {
	if o == nil || IsNil(o.CategoryId.Get()) {
		var ret string
		return ret
	}
	return *o.CategoryId.Get()
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetCategoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CategoryId.Get(), o.CategoryId.IsSet()
}

// HasCategoryId returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasCategoryId() bool {
	if o != nil && o.CategoryId.IsSet() {
		return true
	}

	return false
}

// SetCategoryId gets a reference to the given NullableString and assigns it to the CategoryId field.
func (o *ItemToCompareCartRecordDto) SetCategoryId(v string) {
	o.CategoryId.Set(&v)
}
// SetCategoryIdNil sets the value for CategoryId to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetCategoryIdNil() {
	o.CategoryId.Set(nil)
}

// UnsetCategoryId ensures that no value is present for CategoryId, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetCategoryId() {
	o.CategoryId.Unset()
}

// GetGoogleCategoryId returns the GoogleCategoryId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetGoogleCategoryId() string {
	if o == nil || IsNil(o.GoogleCategoryId.Get()) {
		var ret string
		return ret
	}
	return *o.GoogleCategoryId.Get()
}

// GetGoogleCategoryIdOk returns a tuple with the GoogleCategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetGoogleCategoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GoogleCategoryId.Get(), o.GoogleCategoryId.IsSet()
}

// HasGoogleCategoryId returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasGoogleCategoryId() bool {
	if o != nil && o.GoogleCategoryId.IsSet() {
		return true
	}

	return false
}

// SetGoogleCategoryId gets a reference to the given NullableString and assigns it to the GoogleCategoryId field.
func (o *ItemToCompareCartRecordDto) SetGoogleCategoryId(v string) {
	o.GoogleCategoryId.Set(&v)
}
// SetGoogleCategoryIdNil sets the value for GoogleCategoryId to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetGoogleCategoryIdNil() {
	o.GoogleCategoryId.Set(nil)
}

// UnsetGoogleCategoryId ensures that no value is present for GoogleCategoryId, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetGoogleCategoryId() {
	o.GoogleCategoryId.Unset()
}

// GetGoogleCategoryName returns the GoogleCategoryName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetGoogleCategoryName() string {
	if o == nil || IsNil(o.GoogleCategoryName.Get()) {
		var ret string
		return ret
	}
	return *o.GoogleCategoryName.Get()
}

// GetGoogleCategoryNameOk returns a tuple with the GoogleCategoryName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetGoogleCategoryNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GoogleCategoryName.Get(), o.GoogleCategoryName.IsSet()
}

// HasGoogleCategoryName returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasGoogleCategoryName() bool {
	if o != nil && o.GoogleCategoryName.IsSet() {
		return true
	}

	return false
}

// SetGoogleCategoryName gets a reference to the given NullableString and assigns it to the GoogleCategoryName field.
func (o *ItemToCompareCartRecordDto) SetGoogleCategoryName(v string) {
	o.GoogleCategoryName.Set(&v)
}
// SetGoogleCategoryNameNil sets the value for GoogleCategoryName to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetGoogleCategoryNameNil() {
	o.GoogleCategoryName.Set(nil)
}

// UnsetGoogleCategoryName ensures that no value is present for GoogleCategoryName, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetGoogleCategoryName() {
	o.GoogleCategoryName.Unset()
}

// GetTotalTaxesInUsd returns the TotalTaxesInUsd field value if set, zero value otherwise.
func (o *ItemToCompareCartRecordDto) GetTotalTaxesInUsd() float64 {
	if o == nil || IsNil(o.TotalTaxesInUsd) {
		var ret float64
		return ret
	}
	return *o.TotalTaxesInUsd
}

// GetTotalTaxesInUsdOk returns a tuple with the TotalTaxesInUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemToCompareCartRecordDto) GetTotalTaxesInUsdOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalTaxesInUsd) {
		return nil, false
	}
	return o.TotalTaxesInUsd, true
}

// HasTotalTaxesInUsd returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasTotalTaxesInUsd() bool {
	if o != nil && !IsNil(o.TotalTaxesInUsd) {
		return true
	}

	return false
}

// SetTotalTaxesInUsd gets a reference to the given float64 and assigns it to the TotalTaxesInUsd field.
func (o *ItemToCompareCartRecordDto) SetTotalTaxesInUsd(v float64) {
	o.TotalTaxesInUsd = &v
}

// GetTotalPriceInUsd returns the TotalPriceInUsd field value if set, zero value otherwise.
func (o *ItemToCompareCartRecordDto) GetTotalPriceInUsd() float64 {
	if o == nil || IsNil(o.TotalPriceInUsd) {
		var ret float64
		return ret
	}
	return *o.TotalPriceInUsd
}

// GetTotalPriceInUsdOk returns a tuple with the TotalPriceInUsd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ItemToCompareCartRecordDto) GetTotalPriceInUsdOk() (*float64, bool) {
	if o == nil || IsNil(o.TotalPriceInUsd) {
		return nil, false
	}
	return o.TotalPriceInUsd, true
}

// HasTotalPriceInUsd returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasTotalPriceInUsd() bool {
	if o != nil && !IsNil(o.TotalPriceInUsd) {
		return true
	}

	return false
}

// SetTotalPriceInUsd gets a reference to the given float64 and assigns it to the TotalPriceInUsd field.
func (o *ItemToCompareCartRecordDto) SetTotalPriceInUsd(v float64) {
	o.TotalPriceInUsd = &v
}

// GetShippingCountryId returns the ShippingCountryId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetShippingCountryId() string {
	if o == nil || IsNil(o.ShippingCountryId.Get()) {
		var ret string
		return ret
	}
	return *o.ShippingCountryId.Get()
}

// GetShippingCountryIdOk returns a tuple with the ShippingCountryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetShippingCountryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShippingCountryId.Get(), o.ShippingCountryId.IsSet()
}

// HasShippingCountryId returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasShippingCountryId() bool {
	if o != nil && o.ShippingCountryId.IsSet() {
		return true
	}

	return false
}

// SetShippingCountryId gets a reference to the given NullableString and assigns it to the ShippingCountryId field.
func (o *ItemToCompareCartRecordDto) SetShippingCountryId(v string) {
	o.ShippingCountryId.Set(&v)
}
// SetShippingCountryIdNil sets the value for ShippingCountryId to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetShippingCountryIdNil() {
	o.ShippingCountryId.Set(nil)
}

// UnsetShippingCountryId ensures that no value is present for ShippingCountryId, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetShippingCountryId() {
	o.ShippingCountryId.Unset()
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ItemToCompareCartRecordDto) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ItemToCompareCartRecordDto) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *ItemToCompareCartRecordDto) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *ItemToCompareCartRecordDto) SetTenantId(v string) {
	o.TenantId.Set(&v)
}
// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *ItemToCompareCartRecordDto) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *ItemToCompareCartRecordDto) UnsetTenantId() {
	o.TenantId.Unset()
}

func (o ItemToCompareCartRecordDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ItemToCompareCartRecordDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.CartId.IsSet() {
		toSerialize["cartId"] = o.CartId.Get()
	}
	if o.ItemId.IsSet() {
		toSerialize["itemId"] = o.ItemId.Get()
	}
	if o.ItemTitle.IsSet() {
		toSerialize["itemTitle"] = o.ItemTitle.Get()
	}
	if o.ItemShortDescription.IsSet() {
		toSerialize["itemShortDescription"] = o.ItemShortDescription.Get()
	}
	if o.ItemPrimaryImageUrl.IsSet() {
		toSerialize["itemPrimaryImageUrl"] = o.ItemPrimaryImageUrl.Get()
	}
	if o.BrandId.IsSet() {
		toSerialize["brandId"] = o.BrandId.Get()
	}
	if o.BrandName.IsSet() {
		toSerialize["brandName"] = o.BrandName.Get()
	}
	if o.CategoryName.IsSet() {
		toSerialize["categoryName"] = o.CategoryName.Get()
	}
	if o.CategoryId.IsSet() {
		toSerialize["categoryId"] = o.CategoryId.Get()
	}
	if o.GoogleCategoryId.IsSet() {
		toSerialize["googleCategoryId"] = o.GoogleCategoryId.Get()
	}
	if o.GoogleCategoryName.IsSet() {
		toSerialize["googleCategoryName"] = o.GoogleCategoryName.Get()
	}
	if !IsNil(o.TotalTaxesInUsd) {
		toSerialize["totalTaxesInUsd"] = o.TotalTaxesInUsd
	}
	if !IsNil(o.TotalPriceInUsd) {
		toSerialize["totalPriceInUsd"] = o.TotalPriceInUsd
	}
	if o.ShippingCountryId.IsSet() {
		toSerialize["shippingCountryId"] = o.ShippingCountryId.Get()
	}
	if o.TenantId.IsSet() {
		toSerialize["tenantId"] = o.TenantId.Get()
	}
	return toSerialize, nil
}

type NullableItemToCompareCartRecordDto struct {
	value *ItemToCompareCartRecordDto
	isSet bool
}

func (v NullableItemToCompareCartRecordDto) Get() *ItemToCompareCartRecordDto {
	return v.value
}

func (v *NullableItemToCompareCartRecordDto) Set(val *ItemToCompareCartRecordDto) {
	v.value = val
	v.isSet = true
}

func (v NullableItemToCompareCartRecordDto) IsSet() bool {
	return v.isSet
}

func (v *NullableItemToCompareCartRecordDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableItemToCompareCartRecordDto(val *ItemToCompareCartRecordDto) *NullableItemToCompareCartRecordDto {
	return &NullableItemToCompareCartRecordDto{value: val, isSet: true}
}

func (v NullableItemToCompareCartRecordDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableItemToCompareCartRecordDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


