/*
MarketingService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the EmailTemplateCreateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailTemplateCreateDto{}

// EmailTemplateCreateDto struct for EmailTemplateCreateDto
type EmailTemplateCreateDto struct {
	Id *string `json:"id,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Title string `json:"title"`
	Published *bool `json:"published,omitempty"`
	Description NullableString `json:"description,omitempty"`
	Code NullableString `json:"code,omitempty"`
	Markup NullableString `json:"markup,omitempty"`
	FeaturedImageUrl NullableString `json:"featuredImageUrl,omitempty"`
	CodeType NullableString `json:"codeType,omitempty"`
	MarketingCampaignId NullableString `json:"marketingCampaignId,omitempty"`
}

type _EmailTemplateCreateDto EmailTemplateCreateDto

// NewEmailTemplateCreateDto instantiates a new EmailTemplateCreateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailTemplateCreateDto(title string) *EmailTemplateCreateDto {
	this := EmailTemplateCreateDto{}
	this.Title = title
	return &this
}

// NewEmailTemplateCreateDtoWithDefaults instantiates a new EmailTemplateCreateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailTemplateCreateDtoWithDefaults() *EmailTemplateCreateDto {
	this := EmailTemplateCreateDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EmailTemplateCreateDto) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailTemplateCreateDto) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EmailTemplateCreateDto) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EmailTemplateCreateDto) SetId(v string) {
	o.Id = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *EmailTemplateCreateDto) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailTemplateCreateDto) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *EmailTemplateCreateDto) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *EmailTemplateCreateDto) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

// GetTitle returns the Title field value
func (o *EmailTemplateCreateDto) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *EmailTemplateCreateDto) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *EmailTemplateCreateDto) SetTitle(v string) {
	o.Title = v
}

// GetPublished returns the Published field value if set, zero value otherwise.
func (o *EmailTemplateCreateDto) GetPublished() bool {
	if o == nil || IsNil(o.Published) {
		var ret bool
		return ret
	}
	return *o.Published
}

// GetPublishedOk returns a tuple with the Published field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailTemplateCreateDto) GetPublishedOk() (*bool, bool) {
	if o == nil || IsNil(o.Published) {
		return nil, false
	}
	return o.Published, true
}

// HasPublished returns a boolean if a field has been set.
func (o *EmailTemplateCreateDto) HasPublished() bool {
	if o != nil && !IsNil(o.Published) {
		return true
	}

	return false
}

// SetPublished gets a reference to the given bool and assigns it to the Published field.
func (o *EmailTemplateCreateDto) SetPublished(v bool) {
	o.Published = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailTemplateCreateDto) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailTemplateCreateDto) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *EmailTemplateCreateDto) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *EmailTemplateCreateDto) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *EmailTemplateCreateDto) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *EmailTemplateCreateDto) UnsetDescription() {
	o.Description.Unset()
}

// GetCode returns the Code field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailTemplateCreateDto) GetCode() string {
	if o == nil || IsNil(o.Code.Get()) {
		var ret string
		return ret
	}
	return *o.Code.Get()
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailTemplateCreateDto) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Code.Get(), o.Code.IsSet()
}

// HasCode returns a boolean if a field has been set.
func (o *EmailTemplateCreateDto) HasCode() bool {
	if o != nil && o.Code.IsSet() {
		return true
	}

	return false
}

// SetCode gets a reference to the given NullableString and assigns it to the Code field.
func (o *EmailTemplateCreateDto) SetCode(v string) {
	o.Code.Set(&v)
}
// SetCodeNil sets the value for Code to be an explicit nil
func (o *EmailTemplateCreateDto) SetCodeNil() {
	o.Code.Set(nil)
}

// UnsetCode ensures that no value is present for Code, not even an explicit nil
func (o *EmailTemplateCreateDto) UnsetCode() {
	o.Code.Unset()
}

// GetMarkup returns the Markup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailTemplateCreateDto) GetMarkup() string {
	if o == nil || IsNil(o.Markup.Get()) {
		var ret string
		return ret
	}
	return *o.Markup.Get()
}

// GetMarkupOk returns a tuple with the Markup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailTemplateCreateDto) GetMarkupOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Markup.Get(), o.Markup.IsSet()
}

// HasMarkup returns a boolean if a field has been set.
func (o *EmailTemplateCreateDto) HasMarkup() bool {
	if o != nil && o.Markup.IsSet() {
		return true
	}

	return false
}

// SetMarkup gets a reference to the given NullableString and assigns it to the Markup field.
func (o *EmailTemplateCreateDto) SetMarkup(v string) {
	o.Markup.Set(&v)
}
// SetMarkupNil sets the value for Markup to be an explicit nil
func (o *EmailTemplateCreateDto) SetMarkupNil() {
	o.Markup.Set(nil)
}

// UnsetMarkup ensures that no value is present for Markup, not even an explicit nil
func (o *EmailTemplateCreateDto) UnsetMarkup() {
	o.Markup.Unset()
}

// GetFeaturedImageUrl returns the FeaturedImageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailTemplateCreateDto) GetFeaturedImageUrl() string {
	if o == nil || IsNil(o.FeaturedImageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.FeaturedImageUrl.Get()
}

// GetFeaturedImageUrlOk returns a tuple with the FeaturedImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailTemplateCreateDto) GetFeaturedImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FeaturedImageUrl.Get(), o.FeaturedImageUrl.IsSet()
}

// HasFeaturedImageUrl returns a boolean if a field has been set.
func (o *EmailTemplateCreateDto) HasFeaturedImageUrl() bool {
	if o != nil && o.FeaturedImageUrl.IsSet() {
		return true
	}

	return false
}

// SetFeaturedImageUrl gets a reference to the given NullableString and assigns it to the FeaturedImageUrl field.
func (o *EmailTemplateCreateDto) SetFeaturedImageUrl(v string) {
	o.FeaturedImageUrl.Set(&v)
}
// SetFeaturedImageUrlNil sets the value for FeaturedImageUrl to be an explicit nil
func (o *EmailTemplateCreateDto) SetFeaturedImageUrlNil() {
	o.FeaturedImageUrl.Set(nil)
}

// UnsetFeaturedImageUrl ensures that no value is present for FeaturedImageUrl, not even an explicit nil
func (o *EmailTemplateCreateDto) UnsetFeaturedImageUrl() {
	o.FeaturedImageUrl.Unset()
}

// GetCodeType returns the CodeType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailTemplateCreateDto) GetCodeType() string {
	if o == nil || IsNil(o.CodeType.Get()) {
		var ret string
		return ret
	}
	return *o.CodeType.Get()
}

// GetCodeTypeOk returns a tuple with the CodeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailTemplateCreateDto) GetCodeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CodeType.Get(), o.CodeType.IsSet()
}

// HasCodeType returns a boolean if a field has been set.
func (o *EmailTemplateCreateDto) HasCodeType() bool {
	if o != nil && o.CodeType.IsSet() {
		return true
	}

	return false
}

// SetCodeType gets a reference to the given NullableString and assigns it to the CodeType field.
func (o *EmailTemplateCreateDto) SetCodeType(v string) {
	o.CodeType.Set(&v)
}
// SetCodeTypeNil sets the value for CodeType to be an explicit nil
func (o *EmailTemplateCreateDto) SetCodeTypeNil() {
	o.CodeType.Set(nil)
}

// UnsetCodeType ensures that no value is present for CodeType, not even an explicit nil
func (o *EmailTemplateCreateDto) UnsetCodeType() {
	o.CodeType.Unset()
}

// GetMarketingCampaignId returns the MarketingCampaignId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailTemplateCreateDto) GetMarketingCampaignId() string {
	if o == nil || IsNil(o.MarketingCampaignId.Get()) {
		var ret string
		return ret
	}
	return *o.MarketingCampaignId.Get()
}

// GetMarketingCampaignIdOk returns a tuple with the MarketingCampaignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailTemplateCreateDto) GetMarketingCampaignIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MarketingCampaignId.Get(), o.MarketingCampaignId.IsSet()
}

// HasMarketingCampaignId returns a boolean if a field has been set.
func (o *EmailTemplateCreateDto) HasMarketingCampaignId() bool {
	if o != nil && o.MarketingCampaignId.IsSet() {
		return true
	}

	return false
}

// SetMarketingCampaignId gets a reference to the given NullableString and assigns it to the MarketingCampaignId field.
func (o *EmailTemplateCreateDto) SetMarketingCampaignId(v string) {
	o.MarketingCampaignId.Set(&v)
}
// SetMarketingCampaignIdNil sets the value for MarketingCampaignId to be an explicit nil
func (o *EmailTemplateCreateDto) SetMarketingCampaignIdNil() {
	o.MarketingCampaignId.Set(nil)
}

// UnsetMarketingCampaignId ensures that no value is present for MarketingCampaignId, not even an explicit nil
func (o *EmailTemplateCreateDto) UnsetMarketingCampaignId() {
	o.MarketingCampaignId.Unset()
}

func (o EmailTemplateCreateDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailTemplateCreateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	toSerialize["title"] = o.Title
	if !IsNil(o.Published) {
		toSerialize["published"] = o.Published
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Code.IsSet() {
		toSerialize["code"] = o.Code.Get()
	}
	if o.Markup.IsSet() {
		toSerialize["markup"] = o.Markup.Get()
	}
	if o.FeaturedImageUrl.IsSet() {
		toSerialize["featuredImageUrl"] = o.FeaturedImageUrl.Get()
	}
	if o.CodeType.IsSet() {
		toSerialize["codeType"] = o.CodeType.Get()
	}
	if o.MarketingCampaignId.IsSet() {
		toSerialize["marketingCampaignId"] = o.MarketingCampaignId.Get()
	}
	return toSerialize, nil
}

func (o *EmailTemplateCreateDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailTemplateCreateDto := _EmailTemplateCreateDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailTemplateCreateDto)

	if err != nil {
		return err
	}

	*o = EmailTemplateCreateDto(varEmailTemplateCreateDto)

	return err
}

type NullableEmailTemplateCreateDto struct {
	value *EmailTemplateCreateDto
	isSet bool
}

func (v NullableEmailTemplateCreateDto) Get() *EmailTemplateCreateDto {
	return v.value
}

func (v *NullableEmailTemplateCreateDto) Set(val *EmailTemplateCreateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailTemplateCreateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailTemplateCreateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailTemplateCreateDto(val *EmailTemplateCreateDto) *NullableEmailTemplateCreateDto {
	return &NullableEmailTemplateCreateDto{value: val, isSet: true}
}

func (v NullableEmailTemplateCreateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailTemplateCreateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


