/*
IntelligenceService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the CognitiveAgentSkillDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CognitiveAgentSkillDto{}

// CognitiveAgentSkillDto struct for CognitiveAgentSkillDto
type CognitiveAgentSkillDto struct {
	Id NullableString `json:"id,omitempty"`
	Timestamp NullableTime `json:"timestamp,omitempty"`
	CognitiveAgentId NullableString `json:"cognitiveAgentId,omitempty"`
	CognitiveSkillId NullableString `json:"cognitiveSkillId,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	ConfigJson NullableString `json:"configJson,omitempty"`
	TenantId NullableString `json:"tenantId,omitempty"`
	EnrollmentId NullableString `json:"enrollmentId,omitempty"`
}

// NewCognitiveAgentSkillDto instantiates a new CognitiveAgentSkillDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCognitiveAgentSkillDto() *CognitiveAgentSkillDto {
	this := CognitiveAgentSkillDto{}
	return &this
}

// NewCognitiveAgentSkillDtoWithDefaults instantiates a new CognitiveAgentSkillDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCognitiveAgentSkillDtoWithDefaults() *CognitiveAgentSkillDto {
	this := CognitiveAgentSkillDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CognitiveAgentSkillDto) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CognitiveAgentSkillDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *CognitiveAgentSkillDto) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *CognitiveAgentSkillDto) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *CognitiveAgentSkillDto) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *CognitiveAgentSkillDto) UnsetId() {
	o.Id.Unset()
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CognitiveAgentSkillDto) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CognitiveAgentSkillDto) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *CognitiveAgentSkillDto) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableTime and assigns it to the Timestamp field.
func (o *CognitiveAgentSkillDto) SetTimestamp(v time.Time) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *CognitiveAgentSkillDto) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *CognitiveAgentSkillDto) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetCognitiveAgentId returns the CognitiveAgentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CognitiveAgentSkillDto) GetCognitiveAgentId() string {
	if o == nil || IsNil(o.CognitiveAgentId.Get()) {
		var ret string
		return ret
	}
	return *o.CognitiveAgentId.Get()
}

// GetCognitiveAgentIdOk returns a tuple with the CognitiveAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CognitiveAgentSkillDto) GetCognitiveAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CognitiveAgentId.Get(), o.CognitiveAgentId.IsSet()
}

// HasCognitiveAgentId returns a boolean if a field has been set.
func (o *CognitiveAgentSkillDto) HasCognitiveAgentId() bool {
	if o != nil && o.CognitiveAgentId.IsSet() {
		return true
	}

	return false
}

// SetCognitiveAgentId gets a reference to the given NullableString and assigns it to the CognitiveAgentId field.
func (o *CognitiveAgentSkillDto) SetCognitiveAgentId(v string) {
	o.CognitiveAgentId.Set(&v)
}
// SetCognitiveAgentIdNil sets the value for CognitiveAgentId to be an explicit nil
func (o *CognitiveAgentSkillDto) SetCognitiveAgentIdNil() {
	o.CognitiveAgentId.Set(nil)
}

// UnsetCognitiveAgentId ensures that no value is present for CognitiveAgentId, not even an explicit nil
func (o *CognitiveAgentSkillDto) UnsetCognitiveAgentId() {
	o.CognitiveAgentId.Unset()
}

// GetCognitiveSkillId returns the CognitiveSkillId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CognitiveAgentSkillDto) GetCognitiveSkillId() string {
	if o == nil || IsNil(o.CognitiveSkillId.Get()) {
		var ret string
		return ret
	}
	return *o.CognitiveSkillId.Get()
}

// GetCognitiveSkillIdOk returns a tuple with the CognitiveSkillId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CognitiveAgentSkillDto) GetCognitiveSkillIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CognitiveSkillId.Get(), o.CognitiveSkillId.IsSet()
}

// HasCognitiveSkillId returns a boolean if a field has been set.
func (o *CognitiveAgentSkillDto) HasCognitiveSkillId() bool {
	if o != nil && o.CognitiveSkillId.IsSet() {
		return true
	}

	return false
}

// SetCognitiveSkillId gets a reference to the given NullableString and assigns it to the CognitiveSkillId field.
func (o *CognitiveAgentSkillDto) SetCognitiveSkillId(v string) {
	o.CognitiveSkillId.Set(&v)
}
// SetCognitiveSkillIdNil sets the value for CognitiveSkillId to be an explicit nil
func (o *CognitiveAgentSkillDto) SetCognitiveSkillIdNil() {
	o.CognitiveSkillId.Set(nil)
}

// UnsetCognitiveSkillId ensures that no value is present for CognitiveSkillId, not even an explicit nil
func (o *CognitiveAgentSkillDto) UnsetCognitiveSkillId() {
	o.CognitiveSkillId.Unset()
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CognitiveAgentSkillDto) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CognitiveAgentSkillDto) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CognitiveAgentSkillDto) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CognitiveAgentSkillDto) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetConfigJson returns the ConfigJson field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CognitiveAgentSkillDto) GetConfigJson() string {
	if o == nil || IsNil(o.ConfigJson.Get()) {
		var ret string
		return ret
	}
	return *o.ConfigJson.Get()
}

// GetConfigJsonOk returns a tuple with the ConfigJson field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CognitiveAgentSkillDto) GetConfigJsonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConfigJson.Get(), o.ConfigJson.IsSet()
}

// HasConfigJson returns a boolean if a field has been set.
func (o *CognitiveAgentSkillDto) HasConfigJson() bool {
	if o != nil && o.ConfigJson.IsSet() {
		return true
	}

	return false
}

// SetConfigJson gets a reference to the given NullableString and assigns it to the ConfigJson field.
func (o *CognitiveAgentSkillDto) SetConfigJson(v string) {
	o.ConfigJson.Set(&v)
}
// SetConfigJsonNil sets the value for ConfigJson to be an explicit nil
func (o *CognitiveAgentSkillDto) SetConfigJsonNil() {
	o.ConfigJson.Set(nil)
}

// UnsetConfigJson ensures that no value is present for ConfigJson, not even an explicit nil
func (o *CognitiveAgentSkillDto) UnsetConfigJson() {
	o.ConfigJson.Unset()
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CognitiveAgentSkillDto) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CognitiveAgentSkillDto) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *CognitiveAgentSkillDto) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *CognitiveAgentSkillDto) SetTenantId(v string) {
	o.TenantId.Set(&v)
}
// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *CognitiveAgentSkillDto) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *CognitiveAgentSkillDto) UnsetTenantId() {
	o.TenantId.Unset()
}

// GetEnrollmentId returns the EnrollmentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CognitiveAgentSkillDto) GetEnrollmentId() string {
	if o == nil || IsNil(o.EnrollmentId.Get()) {
		var ret string
		return ret
	}
	return *o.EnrollmentId.Get()
}

// GetEnrollmentIdOk returns a tuple with the EnrollmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CognitiveAgentSkillDto) GetEnrollmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnrollmentId.Get(), o.EnrollmentId.IsSet()
}

// HasEnrollmentId returns a boolean if a field has been set.
func (o *CognitiveAgentSkillDto) HasEnrollmentId() bool {
	if o != nil && o.EnrollmentId.IsSet() {
		return true
	}

	return false
}

// SetEnrollmentId gets a reference to the given NullableString and assigns it to the EnrollmentId field.
func (o *CognitiveAgentSkillDto) SetEnrollmentId(v string) {
	o.EnrollmentId.Set(&v)
}
// SetEnrollmentIdNil sets the value for EnrollmentId to be an explicit nil
func (o *CognitiveAgentSkillDto) SetEnrollmentIdNil() {
	o.EnrollmentId.Set(nil)
}

// UnsetEnrollmentId ensures that no value is present for EnrollmentId, not even an explicit nil
func (o *CognitiveAgentSkillDto) UnsetEnrollmentId() {
	o.EnrollmentId.Unset()
}

func (o CognitiveAgentSkillDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CognitiveAgentSkillDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.CognitiveAgentId.IsSet() {
		toSerialize["cognitiveAgentId"] = o.CognitiveAgentId.Get()
	}
	if o.CognitiveSkillId.IsSet() {
		toSerialize["cognitiveSkillId"] = o.CognitiveSkillId.Get()
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if o.ConfigJson.IsSet() {
		toSerialize["configJson"] = o.ConfigJson.Get()
	}
	if o.TenantId.IsSet() {
		toSerialize["tenantId"] = o.TenantId.Get()
	}
	if o.EnrollmentId.IsSet() {
		toSerialize["enrollmentId"] = o.EnrollmentId.Get()
	}
	return toSerialize, nil
}

type NullableCognitiveAgentSkillDto struct {
	value *CognitiveAgentSkillDto
	isSet bool
}

func (v NullableCognitiveAgentSkillDto) Get() *CognitiveAgentSkillDto {
	return v.value
}

func (v *NullableCognitiveAgentSkillDto) Set(val *CognitiveAgentSkillDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCognitiveAgentSkillDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCognitiveAgentSkillDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCognitiveAgentSkillDto(val *CognitiveAgentSkillDto) *NullableCognitiveAgentSkillDto {
	return &NullableCognitiveAgentSkillDto{value: val, isSet: true}
}

func (v NullableCognitiveAgentSkillDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCognitiveAgentSkillDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


