/*
ShipmentsService

Testing ShippingZonesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_ShippingZonesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ShippingZonesAPIService CreateShippingZoneAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.ShippingZonesAPI.CreateShippingZoneAsync(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShippingZonesAPIService DeleteShippingZoneAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var zoneId string

		httpRes, err := apiClient.ShippingZonesAPI.DeleteShippingZoneAsync(context.Background(), zoneId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShippingZonesAPIService GetShippingZoneByIdAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var zoneId string

		resp, httpRes, err := apiClient.ShippingZonesAPI.GetShippingZoneByIdAsync(context.Background(), zoneId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShippingZonesAPIService GetShippingZonesAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ShippingZonesAPI.GetShippingZonesAsync(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShippingZonesAPIService GetShippingZonesCountAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ShippingZonesAPI.GetShippingZonesCountAsync(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ShippingZonesAPIService UpdateShippingZoneAsync", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var zoneId string

		httpRes, err := apiClient.ShippingZonesAPI.UpdateShippingZoneAsync(context.Background(), zoneId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
