/*
LogisticsService

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0.0
Contact: support@fenix-alliance.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the TruckTripDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TruckTripDto{}

// TruckTripDto struct for TruckTripDto
type TruckTripDto struct {
	Id NullableString `json:"id,omitempty"`
	Timestamp NullableTime `json:"timestamp,omitempty"`
	TripNumber NullableString `json:"tripNumber,omitempty"`
	TruckTripStatus NullableString `json:"truckTripStatus,omitempty"`
	ContainerNumber NullableString `json:"containerNumber,omitempty"`
	SealNumber NullableString `json:"sealNumber,omitempty"`
	DepartureTime NullableTime `json:"departureTime,omitempty"`
	ArrivalTime NullableTime `json:"arrivalTime,omitempty"`
	ActualDepartureTime NullableTime `json:"actualDepartureTime,omitempty"`
	ActualArrivalTime NullableTime `json:"actualArrivalTime,omitempty"`
	DistanceKm NullableFloat64 `json:"distanceKm,omitempty"`
	Notes NullableString `json:"notes,omitempty"`
	TruckId NullableString `json:"truckId,omitempty"`
	OriginPortId NullableString `json:"originPortId,omitempty"`
	OriginLocationId NullableString `json:"originLocationId,omitempty"`
	DestinationPortId NullableString `json:"destinationPortId,omitempty"`
	DestinationLocationId NullableString `json:"destinationLocationId,omitempty"`
	ShipmentId NullableString `json:"shipmentId,omitempty"`
	BillOfLadingId NullableString `json:"billOfLadingId,omitempty"`
	TenantId NullableString `json:"tenantId,omitempty"`
	EnrollmentId NullableString `json:"enrollmentId,omitempty"`
}

// NewTruckTripDto instantiates a new TruckTripDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTruckTripDto() *TruckTripDto {
	this := TruckTripDto{}
	return &this
}

// NewTruckTripDtoWithDefaults instantiates a new TruckTripDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTruckTripDtoWithDefaults() *TruckTripDto {
	this := TruckTripDto{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *TruckTripDto) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *TruckTripDto) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *TruckTripDto) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *TruckTripDto) UnsetId() {
	o.Id.Unset()
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *TruckTripDto) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableTime and assigns it to the Timestamp field.
func (o *TruckTripDto) SetTimestamp(v time.Time) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *TruckTripDto) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *TruckTripDto) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetTripNumber returns the TripNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetTripNumber() string {
	if o == nil || IsNil(o.TripNumber.Get()) {
		var ret string
		return ret
	}
	return *o.TripNumber.Get()
}

// GetTripNumberOk returns a tuple with the TripNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetTripNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TripNumber.Get(), o.TripNumber.IsSet()
}

// HasTripNumber returns a boolean if a field has been set.
func (o *TruckTripDto) HasTripNumber() bool {
	if o != nil && o.TripNumber.IsSet() {
		return true
	}

	return false
}

// SetTripNumber gets a reference to the given NullableString and assigns it to the TripNumber field.
func (o *TruckTripDto) SetTripNumber(v string) {
	o.TripNumber.Set(&v)
}
// SetTripNumberNil sets the value for TripNumber to be an explicit nil
func (o *TruckTripDto) SetTripNumberNil() {
	o.TripNumber.Set(nil)
}

// UnsetTripNumber ensures that no value is present for TripNumber, not even an explicit nil
func (o *TruckTripDto) UnsetTripNumber() {
	o.TripNumber.Unset()
}

// GetTruckTripStatus returns the TruckTripStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetTruckTripStatus() string {
	if o == nil || IsNil(o.TruckTripStatus.Get()) {
		var ret string
		return ret
	}
	return *o.TruckTripStatus.Get()
}

// GetTruckTripStatusOk returns a tuple with the TruckTripStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetTruckTripStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TruckTripStatus.Get(), o.TruckTripStatus.IsSet()
}

// HasTruckTripStatus returns a boolean if a field has been set.
func (o *TruckTripDto) HasTruckTripStatus() bool {
	if o != nil && o.TruckTripStatus.IsSet() {
		return true
	}

	return false
}

// SetTruckTripStatus gets a reference to the given NullableString and assigns it to the TruckTripStatus field.
func (o *TruckTripDto) SetTruckTripStatus(v string) {
	o.TruckTripStatus.Set(&v)
}
// SetTruckTripStatusNil sets the value for TruckTripStatus to be an explicit nil
func (o *TruckTripDto) SetTruckTripStatusNil() {
	o.TruckTripStatus.Set(nil)
}

// UnsetTruckTripStatus ensures that no value is present for TruckTripStatus, not even an explicit nil
func (o *TruckTripDto) UnsetTruckTripStatus() {
	o.TruckTripStatus.Unset()
}

// GetContainerNumber returns the ContainerNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetContainerNumber() string {
	if o == nil || IsNil(o.ContainerNumber.Get()) {
		var ret string
		return ret
	}
	return *o.ContainerNumber.Get()
}

// GetContainerNumberOk returns a tuple with the ContainerNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetContainerNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ContainerNumber.Get(), o.ContainerNumber.IsSet()
}

// HasContainerNumber returns a boolean if a field has been set.
func (o *TruckTripDto) HasContainerNumber() bool {
	if o != nil && o.ContainerNumber.IsSet() {
		return true
	}

	return false
}

// SetContainerNumber gets a reference to the given NullableString and assigns it to the ContainerNumber field.
func (o *TruckTripDto) SetContainerNumber(v string) {
	o.ContainerNumber.Set(&v)
}
// SetContainerNumberNil sets the value for ContainerNumber to be an explicit nil
func (o *TruckTripDto) SetContainerNumberNil() {
	o.ContainerNumber.Set(nil)
}

// UnsetContainerNumber ensures that no value is present for ContainerNumber, not even an explicit nil
func (o *TruckTripDto) UnsetContainerNumber() {
	o.ContainerNumber.Unset()
}

// GetSealNumber returns the SealNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetSealNumber() string {
	if o == nil || IsNil(o.SealNumber.Get()) {
		var ret string
		return ret
	}
	return *o.SealNumber.Get()
}

// GetSealNumberOk returns a tuple with the SealNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetSealNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SealNumber.Get(), o.SealNumber.IsSet()
}

// HasSealNumber returns a boolean if a field has been set.
func (o *TruckTripDto) HasSealNumber() bool {
	if o != nil && o.SealNumber.IsSet() {
		return true
	}

	return false
}

// SetSealNumber gets a reference to the given NullableString and assigns it to the SealNumber field.
func (o *TruckTripDto) SetSealNumber(v string) {
	o.SealNumber.Set(&v)
}
// SetSealNumberNil sets the value for SealNumber to be an explicit nil
func (o *TruckTripDto) SetSealNumberNil() {
	o.SealNumber.Set(nil)
}

// UnsetSealNumber ensures that no value is present for SealNumber, not even an explicit nil
func (o *TruckTripDto) UnsetSealNumber() {
	o.SealNumber.Unset()
}

// GetDepartureTime returns the DepartureTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetDepartureTime() time.Time {
	if o == nil || IsNil(o.DepartureTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DepartureTime.Get()
}

// GetDepartureTimeOk returns a tuple with the DepartureTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetDepartureTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DepartureTime.Get(), o.DepartureTime.IsSet()
}

// HasDepartureTime returns a boolean if a field has been set.
func (o *TruckTripDto) HasDepartureTime() bool {
	if o != nil && o.DepartureTime.IsSet() {
		return true
	}

	return false
}

// SetDepartureTime gets a reference to the given NullableTime and assigns it to the DepartureTime field.
func (o *TruckTripDto) SetDepartureTime(v time.Time) {
	o.DepartureTime.Set(&v)
}
// SetDepartureTimeNil sets the value for DepartureTime to be an explicit nil
func (o *TruckTripDto) SetDepartureTimeNil() {
	o.DepartureTime.Set(nil)
}

// UnsetDepartureTime ensures that no value is present for DepartureTime, not even an explicit nil
func (o *TruckTripDto) UnsetDepartureTime() {
	o.DepartureTime.Unset()
}

// GetArrivalTime returns the ArrivalTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetArrivalTime() time.Time {
	if o == nil || IsNil(o.ArrivalTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ArrivalTime.Get()
}

// GetArrivalTimeOk returns a tuple with the ArrivalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetArrivalTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArrivalTime.Get(), o.ArrivalTime.IsSet()
}

// HasArrivalTime returns a boolean if a field has been set.
func (o *TruckTripDto) HasArrivalTime() bool {
	if o != nil && o.ArrivalTime.IsSet() {
		return true
	}

	return false
}

// SetArrivalTime gets a reference to the given NullableTime and assigns it to the ArrivalTime field.
func (o *TruckTripDto) SetArrivalTime(v time.Time) {
	o.ArrivalTime.Set(&v)
}
// SetArrivalTimeNil sets the value for ArrivalTime to be an explicit nil
func (o *TruckTripDto) SetArrivalTimeNil() {
	o.ArrivalTime.Set(nil)
}

// UnsetArrivalTime ensures that no value is present for ArrivalTime, not even an explicit nil
func (o *TruckTripDto) UnsetArrivalTime() {
	o.ArrivalTime.Unset()
}

// GetActualDepartureTime returns the ActualDepartureTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetActualDepartureTime() time.Time {
	if o == nil || IsNil(o.ActualDepartureTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ActualDepartureTime.Get()
}

// GetActualDepartureTimeOk returns a tuple with the ActualDepartureTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetActualDepartureTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActualDepartureTime.Get(), o.ActualDepartureTime.IsSet()
}

// HasActualDepartureTime returns a boolean if a field has been set.
func (o *TruckTripDto) HasActualDepartureTime() bool {
	if o != nil && o.ActualDepartureTime.IsSet() {
		return true
	}

	return false
}

// SetActualDepartureTime gets a reference to the given NullableTime and assigns it to the ActualDepartureTime field.
func (o *TruckTripDto) SetActualDepartureTime(v time.Time) {
	o.ActualDepartureTime.Set(&v)
}
// SetActualDepartureTimeNil sets the value for ActualDepartureTime to be an explicit nil
func (o *TruckTripDto) SetActualDepartureTimeNil() {
	o.ActualDepartureTime.Set(nil)
}

// UnsetActualDepartureTime ensures that no value is present for ActualDepartureTime, not even an explicit nil
func (o *TruckTripDto) UnsetActualDepartureTime() {
	o.ActualDepartureTime.Unset()
}

// GetActualArrivalTime returns the ActualArrivalTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetActualArrivalTime() time.Time {
	if o == nil || IsNil(o.ActualArrivalTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ActualArrivalTime.Get()
}

// GetActualArrivalTimeOk returns a tuple with the ActualArrivalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetActualArrivalTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActualArrivalTime.Get(), o.ActualArrivalTime.IsSet()
}

// HasActualArrivalTime returns a boolean if a field has been set.
func (o *TruckTripDto) HasActualArrivalTime() bool {
	if o != nil && o.ActualArrivalTime.IsSet() {
		return true
	}

	return false
}

// SetActualArrivalTime gets a reference to the given NullableTime and assigns it to the ActualArrivalTime field.
func (o *TruckTripDto) SetActualArrivalTime(v time.Time) {
	o.ActualArrivalTime.Set(&v)
}
// SetActualArrivalTimeNil sets the value for ActualArrivalTime to be an explicit nil
func (o *TruckTripDto) SetActualArrivalTimeNil() {
	o.ActualArrivalTime.Set(nil)
}

// UnsetActualArrivalTime ensures that no value is present for ActualArrivalTime, not even an explicit nil
func (o *TruckTripDto) UnsetActualArrivalTime() {
	o.ActualArrivalTime.Unset()
}

// GetDistanceKm returns the DistanceKm field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetDistanceKm() float64 {
	if o == nil || IsNil(o.DistanceKm.Get()) {
		var ret float64
		return ret
	}
	return *o.DistanceKm.Get()
}

// GetDistanceKmOk returns a tuple with the DistanceKm field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetDistanceKmOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.DistanceKm.Get(), o.DistanceKm.IsSet()
}

// HasDistanceKm returns a boolean if a field has been set.
func (o *TruckTripDto) HasDistanceKm() bool {
	if o != nil && o.DistanceKm.IsSet() {
		return true
	}

	return false
}

// SetDistanceKm gets a reference to the given NullableFloat64 and assigns it to the DistanceKm field.
func (o *TruckTripDto) SetDistanceKm(v float64) {
	o.DistanceKm.Set(&v)
}
// SetDistanceKmNil sets the value for DistanceKm to be an explicit nil
func (o *TruckTripDto) SetDistanceKmNil() {
	o.DistanceKm.Set(nil)
}

// UnsetDistanceKm ensures that no value is present for DistanceKm, not even an explicit nil
func (o *TruckTripDto) UnsetDistanceKm() {
	o.DistanceKm.Unset()
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetNotes() string {
	if o == nil || IsNil(o.Notes.Get()) {
		var ret string
		return ret
	}
	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// HasNotes returns a boolean if a field has been set.
func (o *TruckTripDto) HasNotes() bool {
	if o != nil && o.Notes.IsSet() {
		return true
	}

	return false
}

// SetNotes gets a reference to the given NullableString and assigns it to the Notes field.
func (o *TruckTripDto) SetNotes(v string) {
	o.Notes.Set(&v)
}
// SetNotesNil sets the value for Notes to be an explicit nil
func (o *TruckTripDto) SetNotesNil() {
	o.Notes.Set(nil)
}

// UnsetNotes ensures that no value is present for Notes, not even an explicit nil
func (o *TruckTripDto) UnsetNotes() {
	o.Notes.Unset()
}

// GetTruckId returns the TruckId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetTruckId() string {
	if o == nil || IsNil(o.TruckId.Get()) {
		var ret string
		return ret
	}
	return *o.TruckId.Get()
}

// GetTruckIdOk returns a tuple with the TruckId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetTruckIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TruckId.Get(), o.TruckId.IsSet()
}

// HasTruckId returns a boolean if a field has been set.
func (o *TruckTripDto) HasTruckId() bool {
	if o != nil && o.TruckId.IsSet() {
		return true
	}

	return false
}

// SetTruckId gets a reference to the given NullableString and assigns it to the TruckId field.
func (o *TruckTripDto) SetTruckId(v string) {
	o.TruckId.Set(&v)
}
// SetTruckIdNil sets the value for TruckId to be an explicit nil
func (o *TruckTripDto) SetTruckIdNil() {
	o.TruckId.Set(nil)
}

// UnsetTruckId ensures that no value is present for TruckId, not even an explicit nil
func (o *TruckTripDto) UnsetTruckId() {
	o.TruckId.Unset()
}

// GetOriginPortId returns the OriginPortId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetOriginPortId() string {
	if o == nil || IsNil(o.OriginPortId.Get()) {
		var ret string
		return ret
	}
	return *o.OriginPortId.Get()
}

// GetOriginPortIdOk returns a tuple with the OriginPortId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetOriginPortIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginPortId.Get(), o.OriginPortId.IsSet()
}

// HasOriginPortId returns a boolean if a field has been set.
func (o *TruckTripDto) HasOriginPortId() bool {
	if o != nil && o.OriginPortId.IsSet() {
		return true
	}

	return false
}

// SetOriginPortId gets a reference to the given NullableString and assigns it to the OriginPortId field.
func (o *TruckTripDto) SetOriginPortId(v string) {
	o.OriginPortId.Set(&v)
}
// SetOriginPortIdNil sets the value for OriginPortId to be an explicit nil
func (o *TruckTripDto) SetOriginPortIdNil() {
	o.OriginPortId.Set(nil)
}

// UnsetOriginPortId ensures that no value is present for OriginPortId, not even an explicit nil
func (o *TruckTripDto) UnsetOriginPortId() {
	o.OriginPortId.Unset()
}

// GetOriginLocationId returns the OriginLocationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetOriginLocationId() string {
	if o == nil || IsNil(o.OriginLocationId.Get()) {
		var ret string
		return ret
	}
	return *o.OriginLocationId.Get()
}

// GetOriginLocationIdOk returns a tuple with the OriginLocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetOriginLocationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OriginLocationId.Get(), o.OriginLocationId.IsSet()
}

// HasOriginLocationId returns a boolean if a field has been set.
func (o *TruckTripDto) HasOriginLocationId() bool {
	if o != nil && o.OriginLocationId.IsSet() {
		return true
	}

	return false
}

// SetOriginLocationId gets a reference to the given NullableString and assigns it to the OriginLocationId field.
func (o *TruckTripDto) SetOriginLocationId(v string) {
	o.OriginLocationId.Set(&v)
}
// SetOriginLocationIdNil sets the value for OriginLocationId to be an explicit nil
func (o *TruckTripDto) SetOriginLocationIdNil() {
	o.OriginLocationId.Set(nil)
}

// UnsetOriginLocationId ensures that no value is present for OriginLocationId, not even an explicit nil
func (o *TruckTripDto) UnsetOriginLocationId() {
	o.OriginLocationId.Unset()
}

// GetDestinationPortId returns the DestinationPortId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetDestinationPortId() string {
	if o == nil || IsNil(o.DestinationPortId.Get()) {
		var ret string
		return ret
	}
	return *o.DestinationPortId.Get()
}

// GetDestinationPortIdOk returns a tuple with the DestinationPortId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetDestinationPortIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DestinationPortId.Get(), o.DestinationPortId.IsSet()
}

// HasDestinationPortId returns a boolean if a field has been set.
func (o *TruckTripDto) HasDestinationPortId() bool {
	if o != nil && o.DestinationPortId.IsSet() {
		return true
	}

	return false
}

// SetDestinationPortId gets a reference to the given NullableString and assigns it to the DestinationPortId field.
func (o *TruckTripDto) SetDestinationPortId(v string) {
	o.DestinationPortId.Set(&v)
}
// SetDestinationPortIdNil sets the value for DestinationPortId to be an explicit nil
func (o *TruckTripDto) SetDestinationPortIdNil() {
	o.DestinationPortId.Set(nil)
}

// UnsetDestinationPortId ensures that no value is present for DestinationPortId, not even an explicit nil
func (o *TruckTripDto) UnsetDestinationPortId() {
	o.DestinationPortId.Unset()
}

// GetDestinationLocationId returns the DestinationLocationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetDestinationLocationId() string {
	if o == nil || IsNil(o.DestinationLocationId.Get()) {
		var ret string
		return ret
	}
	return *o.DestinationLocationId.Get()
}

// GetDestinationLocationIdOk returns a tuple with the DestinationLocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetDestinationLocationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DestinationLocationId.Get(), o.DestinationLocationId.IsSet()
}

// HasDestinationLocationId returns a boolean if a field has been set.
func (o *TruckTripDto) HasDestinationLocationId() bool {
	if o != nil && o.DestinationLocationId.IsSet() {
		return true
	}

	return false
}

// SetDestinationLocationId gets a reference to the given NullableString and assigns it to the DestinationLocationId field.
func (o *TruckTripDto) SetDestinationLocationId(v string) {
	o.DestinationLocationId.Set(&v)
}
// SetDestinationLocationIdNil sets the value for DestinationLocationId to be an explicit nil
func (o *TruckTripDto) SetDestinationLocationIdNil() {
	o.DestinationLocationId.Set(nil)
}

// UnsetDestinationLocationId ensures that no value is present for DestinationLocationId, not even an explicit nil
func (o *TruckTripDto) UnsetDestinationLocationId() {
	o.DestinationLocationId.Unset()
}

// GetShipmentId returns the ShipmentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetShipmentId() string {
	if o == nil || IsNil(o.ShipmentId.Get()) {
		var ret string
		return ret
	}
	return *o.ShipmentId.Get()
}

// GetShipmentIdOk returns a tuple with the ShipmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetShipmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShipmentId.Get(), o.ShipmentId.IsSet()
}

// HasShipmentId returns a boolean if a field has been set.
func (o *TruckTripDto) HasShipmentId() bool {
	if o != nil && o.ShipmentId.IsSet() {
		return true
	}

	return false
}

// SetShipmentId gets a reference to the given NullableString and assigns it to the ShipmentId field.
func (o *TruckTripDto) SetShipmentId(v string) {
	o.ShipmentId.Set(&v)
}
// SetShipmentIdNil sets the value for ShipmentId to be an explicit nil
func (o *TruckTripDto) SetShipmentIdNil() {
	o.ShipmentId.Set(nil)
}

// UnsetShipmentId ensures that no value is present for ShipmentId, not even an explicit nil
func (o *TruckTripDto) UnsetShipmentId() {
	o.ShipmentId.Unset()
}

// GetBillOfLadingId returns the BillOfLadingId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetBillOfLadingId() string {
	if o == nil || IsNil(o.BillOfLadingId.Get()) {
		var ret string
		return ret
	}
	return *o.BillOfLadingId.Get()
}

// GetBillOfLadingIdOk returns a tuple with the BillOfLadingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetBillOfLadingIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BillOfLadingId.Get(), o.BillOfLadingId.IsSet()
}

// HasBillOfLadingId returns a boolean if a field has been set.
func (o *TruckTripDto) HasBillOfLadingId() bool {
	if o != nil && o.BillOfLadingId.IsSet() {
		return true
	}

	return false
}

// SetBillOfLadingId gets a reference to the given NullableString and assigns it to the BillOfLadingId field.
func (o *TruckTripDto) SetBillOfLadingId(v string) {
	o.BillOfLadingId.Set(&v)
}
// SetBillOfLadingIdNil sets the value for BillOfLadingId to be an explicit nil
func (o *TruckTripDto) SetBillOfLadingIdNil() {
	o.BillOfLadingId.Set(nil)
}

// UnsetBillOfLadingId ensures that no value is present for BillOfLadingId, not even an explicit nil
func (o *TruckTripDto) UnsetBillOfLadingId() {
	o.BillOfLadingId.Unset()
}

// GetTenantId returns the TenantId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetTenantId() string {
	if o == nil || IsNil(o.TenantId.Get()) {
		var ret string
		return ret
	}
	return *o.TenantId.Get()
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TenantId.Get(), o.TenantId.IsSet()
}

// HasTenantId returns a boolean if a field has been set.
func (o *TruckTripDto) HasTenantId() bool {
	if o != nil && o.TenantId.IsSet() {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given NullableString and assigns it to the TenantId field.
func (o *TruckTripDto) SetTenantId(v string) {
	o.TenantId.Set(&v)
}
// SetTenantIdNil sets the value for TenantId to be an explicit nil
func (o *TruckTripDto) SetTenantIdNil() {
	o.TenantId.Set(nil)
}

// UnsetTenantId ensures that no value is present for TenantId, not even an explicit nil
func (o *TruckTripDto) UnsetTenantId() {
	o.TenantId.Unset()
}

// GetEnrollmentId returns the EnrollmentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TruckTripDto) GetEnrollmentId() string {
	if o == nil || IsNil(o.EnrollmentId.Get()) {
		var ret string
		return ret
	}
	return *o.EnrollmentId.Get()
}

// GetEnrollmentIdOk returns a tuple with the EnrollmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TruckTripDto) GetEnrollmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnrollmentId.Get(), o.EnrollmentId.IsSet()
}

// HasEnrollmentId returns a boolean if a field has been set.
func (o *TruckTripDto) HasEnrollmentId() bool {
	if o != nil && o.EnrollmentId.IsSet() {
		return true
	}

	return false
}

// SetEnrollmentId gets a reference to the given NullableString and assigns it to the EnrollmentId field.
func (o *TruckTripDto) SetEnrollmentId(v string) {
	o.EnrollmentId.Set(&v)
}
// SetEnrollmentIdNil sets the value for EnrollmentId to be an explicit nil
func (o *TruckTripDto) SetEnrollmentIdNil() {
	o.EnrollmentId.Set(nil)
}

// UnsetEnrollmentId ensures that no value is present for EnrollmentId, not even an explicit nil
func (o *TruckTripDto) UnsetEnrollmentId() {
	o.EnrollmentId.Unset()
}

func (o TruckTripDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TruckTripDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.TripNumber.IsSet() {
		toSerialize["tripNumber"] = o.TripNumber.Get()
	}
	if o.TruckTripStatus.IsSet() {
		toSerialize["truckTripStatus"] = o.TruckTripStatus.Get()
	}
	if o.ContainerNumber.IsSet() {
		toSerialize["containerNumber"] = o.ContainerNumber.Get()
	}
	if o.SealNumber.IsSet() {
		toSerialize["sealNumber"] = o.SealNumber.Get()
	}
	if o.DepartureTime.IsSet() {
		toSerialize["departureTime"] = o.DepartureTime.Get()
	}
	if o.ArrivalTime.IsSet() {
		toSerialize["arrivalTime"] = o.ArrivalTime.Get()
	}
	if o.ActualDepartureTime.IsSet() {
		toSerialize["actualDepartureTime"] = o.ActualDepartureTime.Get()
	}
	if o.ActualArrivalTime.IsSet() {
		toSerialize["actualArrivalTime"] = o.ActualArrivalTime.Get()
	}
	if o.DistanceKm.IsSet() {
		toSerialize["distanceKm"] = o.DistanceKm.Get()
	}
	if o.Notes.IsSet() {
		toSerialize["notes"] = o.Notes.Get()
	}
	if o.TruckId.IsSet() {
		toSerialize["truckId"] = o.TruckId.Get()
	}
	if o.OriginPortId.IsSet() {
		toSerialize["originPortId"] = o.OriginPortId.Get()
	}
	if o.OriginLocationId.IsSet() {
		toSerialize["originLocationId"] = o.OriginLocationId.Get()
	}
	if o.DestinationPortId.IsSet() {
		toSerialize["destinationPortId"] = o.DestinationPortId.Get()
	}
	if o.DestinationLocationId.IsSet() {
		toSerialize["destinationLocationId"] = o.DestinationLocationId.Get()
	}
	if o.ShipmentId.IsSet() {
		toSerialize["shipmentId"] = o.ShipmentId.Get()
	}
	if o.BillOfLadingId.IsSet() {
		toSerialize["billOfLadingId"] = o.BillOfLadingId.Get()
	}
	if o.TenantId.IsSet() {
		toSerialize["tenantId"] = o.TenantId.Get()
	}
	if o.EnrollmentId.IsSet() {
		toSerialize["enrollmentId"] = o.EnrollmentId.Get()
	}
	return toSerialize, nil
}

type NullableTruckTripDto struct {
	value *TruckTripDto
	isSet bool
}

func (v NullableTruckTripDto) Get() *TruckTripDto {
	return v.value
}

func (v *NullableTruckTripDto) Set(val *TruckTripDto) {
	v.value = val
	v.isSet = true
}

func (v NullableTruckTripDto) IsSet() bool {
	return v.isSet
}

func (v *NullableTruckTripDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTruckTripDto(val *TruckTripDto) *NullableTruckTripDto {
	return &NullableTruckTripDto{value: val, isSet: true}
}

func (v NullableTruckTripDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTruckTripDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


